/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NexthopResponseEOF type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopResponseEOF{}

// NexthopResponseEOF struct for NexthopResponseEOF
type NexthopResponseEOF struct {
	Type *string `json:"type,omitempty"`
	NetworkInstance *string `json:"network_instance,omitempty"`
}

// NewNexthopResponseEOF instantiates a new NexthopResponseEOF object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopResponseEOF() *NexthopResponseEOF {
	this := NexthopResponseEOF{}
	return &this
}

// NewNexthopResponseEOFWithDefaults instantiates a new NexthopResponseEOF object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopResponseEOFWithDefaults() *NexthopResponseEOF {
	this := NexthopResponseEOF{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NexthopResponseEOF) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopResponseEOF) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NexthopResponseEOF) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *NexthopResponseEOF) SetType(v string) {
	o.Type = &v
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *NexthopResponseEOF) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopResponseEOF) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *NexthopResponseEOF) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *NexthopResponseEOF) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

func (o NexthopResponseEOF) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopResponseEOF) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.NetworkInstance) {
		toSerialize["network_instance"] = o.NetworkInstance
	}
	return toSerialize, nil
}

type NullableNexthopResponseEOF struct {
	value *NexthopResponseEOF
	isSet bool
}

func (v NullableNexthopResponseEOF) Get() *NexthopResponseEOF {
	return v.value
}

func (v *NullableNexthopResponseEOF) Set(val *NexthopResponseEOF) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopResponseEOF) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopResponseEOF) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopResponseEOF(val *NexthopResponseEOF) *NullableNexthopResponseEOF {
	return &NullableNexthopResponseEOF{value: val, isSet: true}
}

func (v NullableNexthopResponseEOF) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopResponseEOF) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


