/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteRouteItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteRouteItem{}

// DeleteRouteItem struct for DeleteRouteItem
type DeleteRouteItem struct {
	Prefix IpPrefix `json:"prefix"`
	// Address family.
	Afi string `json:"afi"`
	// Operation action.
	Action string `json:"action"`
	RouteType RouteType `json:"route_type"`
	Lsp RouteLspType `json:"lsp"`
}

type _DeleteRouteItem DeleteRouteItem

// NewDeleteRouteItem instantiates a new DeleteRouteItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteRouteItem(prefix IpPrefix, afi string, action string, routeType RouteType, lsp RouteLspType) *DeleteRouteItem {
	this := DeleteRouteItem{}
	this.Prefix = prefix
	this.Afi = afi
	this.Action = action
	this.RouteType = routeType
	this.Lsp = lsp
	return &this
}

// NewDeleteRouteItemWithDefaults instantiates a new DeleteRouteItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteRouteItemWithDefaults() *DeleteRouteItem {
	this := DeleteRouteItem{}
	return &this
}

// GetPrefix returns the Prefix field value
func (o *DeleteRouteItem) GetPrefix() IpPrefix {
	if o == nil {
		var ret IpPrefix
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *DeleteRouteItem) GetPrefixOk() (*IpPrefix, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *DeleteRouteItem) SetPrefix(v IpPrefix) {
	o.Prefix = v
}

// GetAfi returns the Afi field value
func (o *DeleteRouteItem) GetAfi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Afi
}

// GetAfiOk returns a tuple with the Afi field value
// and a boolean to check if the value has been set.
func (o *DeleteRouteItem) GetAfiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Afi, true
}

// SetAfi sets field value
func (o *DeleteRouteItem) SetAfi(v string) {
	o.Afi = v
}

// GetAction returns the Action field value
func (o *DeleteRouteItem) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *DeleteRouteItem) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *DeleteRouteItem) SetAction(v string) {
	o.Action = v
}

// GetRouteType returns the RouteType field value
func (o *DeleteRouteItem) GetRouteType() RouteType {
	if o == nil {
		var ret RouteType
		return ret
	}

	return o.RouteType
}

// GetRouteTypeOk returns a tuple with the RouteType field value
// and a boolean to check if the value has been set.
func (o *DeleteRouteItem) GetRouteTypeOk() (*RouteType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RouteType, true
}

// SetRouteType sets field value
func (o *DeleteRouteItem) SetRouteType(v RouteType) {
	o.RouteType = v
}

// GetLsp returns the Lsp field value
func (o *DeleteRouteItem) GetLsp() RouteLspType {
	if o == nil {
		var ret RouteLspType
		return ret
	}

	return o.Lsp
}

// GetLspOk returns a tuple with the Lsp field value
// and a boolean to check if the value has been set.
func (o *DeleteRouteItem) GetLspOk() (*RouteLspType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lsp, true
}

// SetLsp sets field value
func (o *DeleteRouteItem) SetLsp(v RouteLspType) {
	o.Lsp = v
}

func (o DeleteRouteItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteRouteItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prefix"] = o.Prefix
	toSerialize["afi"] = o.Afi
	toSerialize["action"] = o.Action
	toSerialize["route_type"] = o.RouteType
	toSerialize["lsp"] = o.Lsp
	return toSerialize, nil
}

func (o *DeleteRouteItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prefix",
		"afi",
		"action",
		"route_type",
		"lsp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteRouteItem := _DeleteRouteItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteRouteItem)

	if err != nil {
		return err
	}

	*o = DeleteRouteItem(varDeleteRouteItem)

	return err
}

type NullableDeleteRouteItem struct {
	value *DeleteRouteItem
	isSet bool
}

func (v NullableDeleteRouteItem) Get() *DeleteRouteItem {
	return v.value
}

func (v *NullableDeleteRouteItem) Set(val *DeleteRouteItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteRouteItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteRouteItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteRouteItem(val *DeleteRouteItem) *NullableDeleteRouteItem {
	return &NullableDeleteRouteItem{value: val, isSet: true}
}

func (v NullableDeleteRouteItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteRouteItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


