/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the NexthopNotificationItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopNotificationItem{}

// NexthopNotificationItem struct for NexthopNotificationItem
type NexthopNotificationItem struct {
	NetworkInstance *string `json:"network_instance,omitempty"`
	AddressFamily *string `json:"address_family,omitempty"`
	Address *IpAddress `json:"address,omitempty"`
	ProtocolType *RouteType `json:"protocol_type,omitempty"`
	Flags []string `json:"flags,omitempty"`
	ViaAddress *IpAddress `json:"via_address,omitempty"`
	Metric *int32 `json:"metric,omitempty"`
	ViaNetworkInstance *string `json:"via_network_instance,omitempty"`
	NexthopTimestamp *time.Time `json:"nexthop_timestamp,omitempty"`
}

// NewNexthopNotificationItem instantiates a new NexthopNotificationItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopNotificationItem() *NexthopNotificationItem {
	this := NexthopNotificationItem{}
	return &this
}

// NewNexthopNotificationItemWithDefaults instantiates a new NexthopNotificationItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopNotificationItemWithDefaults() *NexthopNotificationItem {
	this := NexthopNotificationItem{}
	return &this
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *NexthopNotificationItem) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetAddressFamily() string {
	if o == nil || IsNil(o.AddressFamily) {
		var ret string
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetAddressFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.AddressFamily) {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasAddressFamily() bool {
	if o != nil && !IsNil(o.AddressFamily) {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given string and assigns it to the AddressFamily field.
func (o *NexthopNotificationItem) SetAddressFamily(v string) {
	o.AddressFamily = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetAddress() IpAddress {
	if o == nil || IsNil(o.Address) {
		var ret IpAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetAddressOk() (*IpAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given IpAddress and assigns it to the Address field.
func (o *NexthopNotificationItem) SetAddress(v IpAddress) {
	o.Address = &v
}

// GetProtocolType returns the ProtocolType field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetProtocolType() RouteType {
	if o == nil || IsNil(o.ProtocolType) {
		var ret RouteType
		return ret
	}
	return *o.ProtocolType
}

// GetProtocolTypeOk returns a tuple with the ProtocolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetProtocolTypeOk() (*RouteType, bool) {
	if o == nil || IsNil(o.ProtocolType) {
		return nil, false
	}
	return o.ProtocolType, true
}

// HasProtocolType returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasProtocolType() bool {
	if o != nil && !IsNil(o.ProtocolType) {
		return true
	}

	return false
}

// SetProtocolType gets a reference to the given RouteType and assigns it to the ProtocolType field.
func (o *NexthopNotificationItem) SetProtocolType(v RouteType) {
	o.ProtocolType = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetFlags() []string {
	if o == nil || IsNil(o.Flags) {
		var ret []string
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetFlagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *NexthopNotificationItem) SetFlags(v []string) {
	o.Flags = v
}

// GetViaAddress returns the ViaAddress field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetViaAddress() IpAddress {
	if o == nil || IsNil(o.ViaAddress) {
		var ret IpAddress
		return ret
	}
	return *o.ViaAddress
}

// GetViaAddressOk returns a tuple with the ViaAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetViaAddressOk() (*IpAddress, bool) {
	if o == nil || IsNil(o.ViaAddress) {
		return nil, false
	}
	return o.ViaAddress, true
}

// HasViaAddress returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasViaAddress() bool {
	if o != nil && !IsNil(o.ViaAddress) {
		return true
	}

	return false
}

// SetViaAddress gets a reference to the given IpAddress and assigns it to the ViaAddress field.
func (o *NexthopNotificationItem) SetViaAddress(v IpAddress) {
	o.ViaAddress = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetMetric() int32 {
	if o == nil || IsNil(o.Metric) {
		var ret int32
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetMetricOk() (*int32, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given int32 and assigns it to the Metric field.
func (o *NexthopNotificationItem) SetMetric(v int32) {
	o.Metric = &v
}

// GetViaNetworkInstance returns the ViaNetworkInstance field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetViaNetworkInstance() string {
	if o == nil || IsNil(o.ViaNetworkInstance) {
		var ret string
		return ret
	}
	return *o.ViaNetworkInstance
}

// GetViaNetworkInstanceOk returns a tuple with the ViaNetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetViaNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.ViaNetworkInstance) {
		return nil, false
	}
	return o.ViaNetworkInstance, true
}

// HasViaNetworkInstance returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasViaNetworkInstance() bool {
	if o != nil && !IsNil(o.ViaNetworkInstance) {
		return true
	}

	return false
}

// SetViaNetworkInstance gets a reference to the given string and assigns it to the ViaNetworkInstance field.
func (o *NexthopNotificationItem) SetViaNetworkInstance(v string) {
	o.ViaNetworkInstance = &v
}

// GetNexthopTimestamp returns the NexthopTimestamp field value if set, zero value otherwise.
func (o *NexthopNotificationItem) GetNexthopTimestamp() time.Time {
	if o == nil || IsNil(o.NexthopTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.NexthopTimestamp
}

// GetNexthopTimestampOk returns a tuple with the NexthopTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopNotificationItem) GetNexthopTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NexthopTimestamp) {
		return nil, false
	}
	return o.NexthopTimestamp, true
}

// HasNexthopTimestamp returns a boolean if a field has been set.
func (o *NexthopNotificationItem) HasNexthopTimestamp() bool {
	if o != nil && !IsNil(o.NexthopTimestamp) {
		return true
	}

	return false
}

// SetNexthopTimestamp gets a reference to the given time.Time and assigns it to the NexthopTimestamp field.
func (o *NexthopNotificationItem) SetNexthopTimestamp(v time.Time) {
	o.NexthopTimestamp = &v
}

func (o NexthopNotificationItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopNotificationItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkInstance) {
		toSerialize["network_instance"] = o.NetworkInstance
	}
	if !IsNil(o.AddressFamily) {
		toSerialize["address_family"] = o.AddressFamily
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.ProtocolType) {
		toSerialize["protocol_type"] = o.ProtocolType
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.ViaAddress) {
		toSerialize["via_address"] = o.ViaAddress
	}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.ViaNetworkInstance) {
		toSerialize["via_network_instance"] = o.ViaNetworkInstance
	}
	if !IsNil(o.NexthopTimestamp) {
		toSerialize["nexthop_timestamp"] = o.NexthopTimestamp
	}
	return toSerialize, nil
}

type NullableNexthopNotificationItem struct {
	value *NexthopNotificationItem
	isSet bool
}

func (v NullableNexthopNotificationItem) Get() *NexthopNotificationItem {
	return v.value
}

func (v *NullableNexthopNotificationItem) Set(val *NexthopNotificationItem) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopNotificationItem) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopNotificationItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopNotificationItem(val *NexthopNotificationItem) *NullableNexthopNotificationItem {
	return &NullableNexthopNotificationItem{value: val, isSet: true}
}

func (v NullableNexthopNotificationItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopNotificationItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


