/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PublishedNexthopEntryInnerViaNexthopId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedNexthopEntryInnerViaNexthopId{}

// PublishedNexthopEntryInnerViaNexthopId Via nexthop identifer which composed by nexthop networkInstance and nexthop id. If \"entry\" exists, \"viaNexthopId\" is required.
type PublishedNexthopEntryInnerViaNexthopId struct {
	// If \"viaNexthopId\" exists, \"networkInstance\" is required. The networkInstance which via nexthop belongs to.
	NetworkInstance *string `json:"networkInstance,omitempty"`
	// Nexthop id, identify a nexthop. Optional, if \"id\" is empty(none), it means that the current nexthop is the final nexthop.
	Id *int32 `json:"id,omitempty"`
}

// NewPublishedNexthopEntryInnerViaNexthopId instantiates a new PublishedNexthopEntryInnerViaNexthopId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedNexthopEntryInnerViaNexthopId() *PublishedNexthopEntryInnerViaNexthopId {
	this := PublishedNexthopEntryInnerViaNexthopId{}
	return &this
}

// NewPublishedNexthopEntryInnerViaNexthopIdWithDefaults instantiates a new PublishedNexthopEntryInnerViaNexthopId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedNexthopEntryInnerViaNexthopIdWithDefaults() *PublishedNexthopEntryInnerViaNexthopId {
	this := PublishedNexthopEntryInnerViaNexthopId{}
	return &this
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInnerViaNexthopId) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInnerViaNexthopId) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInnerViaNexthopId) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *PublishedNexthopEntryInnerViaNexthopId) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInnerViaNexthopId) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInnerViaNexthopId) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInnerViaNexthopId) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *PublishedNexthopEntryInnerViaNexthopId) SetId(v int32) {
	o.Id = &v
}

func (o PublishedNexthopEntryInnerViaNexthopId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedNexthopEntryInnerViaNexthopId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkInstance) {
		toSerialize["networkInstance"] = o.NetworkInstance
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullablePublishedNexthopEntryInnerViaNexthopId struct {
	value *PublishedNexthopEntryInnerViaNexthopId
	isSet bool
}

func (v NullablePublishedNexthopEntryInnerViaNexthopId) Get() *PublishedNexthopEntryInnerViaNexthopId {
	return v.value
}

func (v *NullablePublishedNexthopEntryInnerViaNexthopId) Set(val *PublishedNexthopEntryInnerViaNexthopId) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedNexthopEntryInnerViaNexthopId) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedNexthopEntryInnerViaNexthopId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedNexthopEntryInnerViaNexthopId(val *PublishedNexthopEntryInnerViaNexthopId) *NullablePublishedNexthopEntryInnerViaNexthopId {
	return &NullablePublishedNexthopEntryInnerViaNexthopId{value: val, isSet: true}
}

func (v NullablePublishedNexthopEntryInnerViaNexthopId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedNexthopEntryInnerViaNexthopId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


