/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RouteLspType if the route is lsp or non-lsp. If not present, the default is non-lsp.
type RouteLspType string

// List of route_lsp_type
const (
	NON_LSP RouteLspType = "non_lsp"
	LSP RouteLspType = "lsp"
)

// All allowed values of RouteLspType enum
var AllowedRouteLspTypeEnumValues = []RouteLspType{
	"non_lsp",
	"lsp",
}

func (v *RouteLspType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RouteLspType(value)
	for _, existing := range AllowedRouteLspTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RouteLspType", value)
}

// NewRouteLspTypeFromValue returns a pointer to a valid RouteLspType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRouteLspTypeFromValue(v string) (*RouteLspType, error) {
	ev := RouteLspType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RouteLspType: valid values are %v", v, AllowedRouteLspTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RouteLspType) IsValid() bool {
	for _, existing := range AllowedRouteLspTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to route_lsp_type value
func (v RouteLspType) Ptr() *RouteLspType {
	return &v
}

type NullableRouteLspType struct {
	value *RouteLspType
	isSet bool
}

func (v NullableRouteLspType) Get() *RouteLspType {
	return v.value
}

func (v *NullableRouteLspType) Set(val *RouteLspType) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteLspType) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteLspType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteLspType(val *RouteLspType) *NullableRouteLspType {
	return &NullableRouteLspType{value: val, isSet: true}
}

func (v NullableRouteLspType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteLspType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

