/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the PublishedRoute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedRoute{}

// PublishedRoute struct for PublishedRoute
type PublishedRoute struct {
	// Operation action.
	Action *string `json:"action,omitempty"`
	// Network instance.
	NetworkInstance *string `json:"network_instance,omitempty"`
	// Address family.
	Afi *string `json:"afi,omitempty"`
	Prefix *IpPrefix `json:"prefix,omitempty"`
	Type *RouteType `json:"type,omitempty"`
	Nh *PublishedRouteNh `json:"nh,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// NewPublishedRoute instantiates a new PublishedRoute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedRoute() *PublishedRoute {
	this := PublishedRoute{}
	return &this
}

// NewPublishedRouteWithDefaults instantiates a new PublishedRoute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedRouteWithDefaults() *PublishedRoute {
	this := PublishedRoute{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *PublishedRoute) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedRoute) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *PublishedRoute) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *PublishedRoute) SetAction(v string) {
	o.Action = &v
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *PublishedRoute) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedRoute) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *PublishedRoute) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *PublishedRoute) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetAfi returns the Afi field value if set, zero value otherwise.
func (o *PublishedRoute) GetAfi() string {
	if o == nil || IsNil(o.Afi) {
		var ret string
		return ret
	}
	return *o.Afi
}

// GetAfiOk returns a tuple with the Afi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedRoute) GetAfiOk() (*string, bool) {
	if o == nil || IsNil(o.Afi) {
		return nil, false
	}
	return o.Afi, true
}

// HasAfi returns a boolean if a field has been set.
func (o *PublishedRoute) HasAfi() bool {
	if o != nil && !IsNil(o.Afi) {
		return true
	}

	return false
}

// SetAfi gets a reference to the given string and assigns it to the Afi field.
func (o *PublishedRoute) SetAfi(v string) {
	o.Afi = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *PublishedRoute) GetPrefix() IpPrefix {
	if o == nil || IsNil(o.Prefix) {
		var ret IpPrefix
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedRoute) GetPrefixOk() (*IpPrefix, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *PublishedRoute) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given IpPrefix and assigns it to the Prefix field.
func (o *PublishedRoute) SetPrefix(v IpPrefix) {
	o.Prefix = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PublishedRoute) GetType() RouteType {
	if o == nil || IsNil(o.Type) {
		var ret RouteType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedRoute) GetTypeOk() (*RouteType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PublishedRoute) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given RouteType and assigns it to the Type field.
func (o *PublishedRoute) SetType(v RouteType) {
	o.Type = &v
}

// GetNh returns the Nh field value if set, zero value otherwise.
func (o *PublishedRoute) GetNh() PublishedRouteNh {
	if o == nil || IsNil(o.Nh) {
		var ret PublishedRouteNh
		return ret
	}
	return *o.Nh
}

// GetNhOk returns a tuple with the Nh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedRoute) GetNhOk() (*PublishedRouteNh, bool) {
	if o == nil || IsNil(o.Nh) {
		return nil, false
	}
	return o.Nh, true
}

// HasNh returns a boolean if a field has been set.
func (o *PublishedRoute) HasNh() bool {
	if o != nil && !IsNil(o.Nh) {
		return true
	}

	return false
}

// SetNh gets a reference to the given PublishedRouteNh and assigns it to the Nh field.
func (o *PublishedRoute) SetNh(v PublishedRouteNh) {
	o.Nh = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *PublishedRoute) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedRoute) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *PublishedRoute) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *PublishedRoute) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o PublishedRoute) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedRoute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.NetworkInstance) {
		toSerialize["network_instance"] = o.NetworkInstance
	}
	if !IsNil(o.Afi) {
		toSerialize["afi"] = o.Afi
	}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Nh) {
		toSerialize["nh"] = o.Nh
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullablePublishedRoute struct {
	value *PublishedRoute
	isSet bool
}

func (v NullablePublishedRoute) Get() *PublishedRoute {
	return v.value
}

func (v *NullablePublishedRoute) Set(val *PublishedRoute) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedRoute) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedRoute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedRoute(val *PublishedRoute) *NullablePublishedRoute {
	return &NullablePublishedRoute{value: val, isSet: true}
}

func (v NullablePublishedRoute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedRoute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


