/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Routes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Routes{}

// Routes struct for Routes
type Routes struct {
	ClientId *ClientIdentifier `json:"client_id,omitempty"`
	Routes []RouteArrayItem `json:"routes,omitempty"`
}

// NewRoutes instantiates a new Routes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutes() *Routes {
	this := Routes{}
	return &this
}

// NewRoutesWithDefaults instantiates a new Routes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesWithDefaults() *Routes {
	this := Routes{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *Routes) GetClientId() ClientIdentifier {
	if o == nil || IsNil(o.ClientId) {
		var ret ClientIdentifier
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Routes) GetClientIdOk() (*ClientIdentifier, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *Routes) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given ClientIdentifier and assigns it to the ClientId field.
func (o *Routes) SetClientId(v ClientIdentifier) {
	o.ClientId = &v
}

// GetRoutes returns the Routes field value if set, zero value otherwise.
func (o *Routes) GetRoutes() []RouteArrayItem {
	if o == nil || IsNil(o.Routes) {
		var ret []RouteArrayItem
		return ret
	}
	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Routes) GetRoutesOk() ([]RouteArrayItem, bool) {
	if o == nil || IsNil(o.Routes) {
		return nil, false
	}
	return o.Routes, true
}

// HasRoutes returns a boolean if a field has been set.
func (o *Routes) HasRoutes() bool {
	if o != nil && !IsNil(o.Routes) {
		return true
	}

	return false
}

// SetRoutes gets a reference to the given []RouteArrayItem and assigns it to the Routes field.
func (o *Routes) SetRoutes(v []RouteArrayItem) {
	o.Routes = v
}

func (o Routes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Routes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.Routes) {
		toSerialize["routes"] = o.Routes
	}
	return toSerialize, nil
}

type NullableRoutes struct {
	value *Routes
	isSet bool
}

func (v NullableRoutes) Get() *Routes {
	return v.value
}

func (v *NullableRoutes) Set(val *Routes) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutes) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutes(val *Routes) *NullableRoutes {
	return &NullableRoutes{value: val, isSet: true}
}

func (v NullableRoutes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


