/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Ipv4Address type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ipv4Address{}

// Ipv4Address struct for Ipv4Address
type Ipv4Address struct {
}

// NewIpv4Address instantiates a new Ipv4Address object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpv4Address() *Ipv4Address {
	this := Ipv4Address{}
	return &this
}

// NewIpv4AddressWithDefaults instantiates a new Ipv4Address object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpv4AddressWithDefaults() *Ipv4Address {
	this := Ipv4Address{}
	return &this
}

func (o Ipv4Address) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ipv4Address) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableIpv4Address struct {
	value *Ipv4Address
	isSet bool
}

func (v NullableIpv4Address) Get() *Ipv4Address {
	return v.value
}

func (v *NullableIpv4Address) Set(val *Ipv4Address) {
	v.value = val
	v.isSet = true
}

func (v NullableIpv4Address) IsSet() bool {
	return v.isSet
}

func (v *NullableIpv4Address) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpv4Address(val *Ipv4Address) *NullableIpv4Address {
	return &NullableIpv4Address{value: val, isSet: true}
}

func (v NullableIpv4Address) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpv4Address) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


