/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PublishedNexthopEntryInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedNexthopEntryInner{}

// PublishedNexthopEntryInner Specific content of nexthop, including via_nh, nh_addr, label.
type PublishedNexthopEntryInner struct {
	ViaNh *PublishedNexthopEntryInnerViaNh `json:"via_nh,omitempty"`
	ViaNexthopId *PublishedNexthopEntryInnerViaNexthopId `json:"viaNexthopId,omitempty"`
	NhAddr *IpAddress `json:"nh_addr,omitempty"`
	// For vpn and mpls label forwarding.
	Label *int32 `json:"label,omitempty"`
	// The networkInstance which nh_addr belongs to.
	NetworkInstance *string `json:"networkInstance,omitempty"`
	IfType *IfType `json:"if_type,omitempty"`
}

// NewPublishedNexthopEntryInner instantiates a new PublishedNexthopEntryInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedNexthopEntryInner() *PublishedNexthopEntryInner {
	this := PublishedNexthopEntryInner{}
	return &this
}

// NewPublishedNexthopEntryInnerWithDefaults instantiates a new PublishedNexthopEntryInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedNexthopEntryInnerWithDefaults() *PublishedNexthopEntryInner {
	this := PublishedNexthopEntryInner{}
	return &this
}

// GetViaNh returns the ViaNh field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInner) GetViaNh() PublishedNexthopEntryInnerViaNh {
	if o == nil || IsNil(o.ViaNh) {
		var ret PublishedNexthopEntryInnerViaNh
		return ret
	}
	return *o.ViaNh
}

// GetViaNhOk returns a tuple with the ViaNh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInner) GetViaNhOk() (*PublishedNexthopEntryInnerViaNh, bool) {
	if o == nil || IsNil(o.ViaNh) {
		return nil, false
	}
	return o.ViaNh, true
}

// HasViaNh returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInner) HasViaNh() bool {
	if o != nil && !IsNil(o.ViaNh) {
		return true
	}

	return false
}

// SetViaNh gets a reference to the given PublishedNexthopEntryInnerViaNh and assigns it to the ViaNh field.
func (o *PublishedNexthopEntryInner) SetViaNh(v PublishedNexthopEntryInnerViaNh) {
	o.ViaNh = &v
}

// GetViaNexthopId returns the ViaNexthopId field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInner) GetViaNexthopId() PublishedNexthopEntryInnerViaNexthopId {
	if o == nil || IsNil(o.ViaNexthopId) {
		var ret PublishedNexthopEntryInnerViaNexthopId
		return ret
	}
	return *o.ViaNexthopId
}

// GetViaNexthopIdOk returns a tuple with the ViaNexthopId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInner) GetViaNexthopIdOk() (*PublishedNexthopEntryInnerViaNexthopId, bool) {
	if o == nil || IsNil(o.ViaNexthopId) {
		return nil, false
	}
	return o.ViaNexthopId, true
}

// HasViaNexthopId returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInner) HasViaNexthopId() bool {
	if o != nil && !IsNil(o.ViaNexthopId) {
		return true
	}

	return false
}

// SetViaNexthopId gets a reference to the given PublishedNexthopEntryInnerViaNexthopId and assigns it to the ViaNexthopId field.
func (o *PublishedNexthopEntryInner) SetViaNexthopId(v PublishedNexthopEntryInnerViaNexthopId) {
	o.ViaNexthopId = &v
}

// GetNhAddr returns the NhAddr field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInner) GetNhAddr() IpAddress {
	if o == nil || IsNil(o.NhAddr) {
		var ret IpAddress
		return ret
	}
	return *o.NhAddr
}

// GetNhAddrOk returns a tuple with the NhAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInner) GetNhAddrOk() (*IpAddress, bool) {
	if o == nil || IsNil(o.NhAddr) {
		return nil, false
	}
	return o.NhAddr, true
}

// HasNhAddr returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInner) HasNhAddr() bool {
	if o != nil && !IsNil(o.NhAddr) {
		return true
	}

	return false
}

// SetNhAddr gets a reference to the given IpAddress and assigns it to the NhAddr field.
func (o *PublishedNexthopEntryInner) SetNhAddr(v IpAddress) {
	o.NhAddr = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInner) GetLabel() int32 {
	if o == nil || IsNil(o.Label) {
		var ret int32
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInner) GetLabelOk() (*int32, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given int32 and assigns it to the Label field.
func (o *PublishedNexthopEntryInner) SetLabel(v int32) {
	o.Label = &v
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInner) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInner) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInner) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *PublishedNexthopEntryInner) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetIfType returns the IfType field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInner) GetIfType() IfType {
	if o == nil || IsNil(o.IfType) {
		var ret IfType
		return ret
	}
	return *o.IfType
}

// GetIfTypeOk returns a tuple with the IfType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInner) GetIfTypeOk() (*IfType, bool) {
	if o == nil || IsNil(o.IfType) {
		return nil, false
	}
	return o.IfType, true
}

// HasIfType returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInner) HasIfType() bool {
	if o != nil && !IsNil(o.IfType) {
		return true
	}

	return false
}

// SetIfType gets a reference to the given IfType and assigns it to the IfType field.
func (o *PublishedNexthopEntryInner) SetIfType(v IfType) {
	o.IfType = &v
}

func (o PublishedNexthopEntryInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedNexthopEntryInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ViaNh) {
		toSerialize["via_nh"] = o.ViaNh
	}
	if !IsNil(o.ViaNexthopId) {
		toSerialize["viaNexthopId"] = o.ViaNexthopId
	}
	if !IsNil(o.NhAddr) {
		toSerialize["nh_addr"] = o.NhAddr
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.NetworkInstance) {
		toSerialize["networkInstance"] = o.NetworkInstance
	}
	if !IsNil(o.IfType) {
		toSerialize["if_type"] = o.IfType
	}
	return toSerialize, nil
}

type NullablePublishedNexthopEntryInner struct {
	value *PublishedNexthopEntryInner
	isSet bool
}

func (v NullablePublishedNexthopEntryInner) Get() *PublishedNexthopEntryInner {
	return v.value
}

func (v *NullablePublishedNexthopEntryInner) Set(val *PublishedNexthopEntryInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedNexthopEntryInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedNexthopEntryInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedNexthopEntryInner(val *PublishedNexthopEntryInner) *NullablePublishedNexthopEntryInner {
	return &NullablePublishedNexthopEntryInner{value: val, isSet: true}
}

func (v NullablePublishedNexthopEntryInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedNexthopEntryInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


