/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IpAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpAddress{}

// IpAddress struct for IpAddress
type IpAddress struct {
}

// NewIpAddress instantiates a new IpAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpAddress() *IpAddress {
	this := IpAddress{}
	return &this
}

// NewIpAddressWithDefaults instantiates a new IpAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpAddressWithDefaults() *IpAddress {
	this := IpAddress{}
	return &this
}

func (o IpAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableIpAddress struct {
	value *IpAddress
	isSet bool
}

func (v NullableIpAddress) Get() *IpAddress {
	return v.value
}

func (v *NullableIpAddress) Set(val *IpAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableIpAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableIpAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpAddress(val *IpAddress) *NullableIpAddress {
	return &NullableIpAddress{value: val, isSet: true}
}

func (v NullableIpAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


