/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PublishedNexthopEntryInnerViaNh type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedNexthopEntryInnerViaNh{}

// PublishedNexthopEntryInnerViaNh Via nexthop identifer which composed by nexthop network_instance and nexthop id. If \"entry\" exists, \"via_nh\" is required.
type PublishedNexthopEntryInnerViaNh struct {
	// If \"via_nh\" exists, \"network_instance\" is required. The network_instance which via nexthop belongs to.
	NetworkInstance *string `json:"network_instance,omitempty"`
	// Nexthop id, identify a nexthop. Optional, if \"id\" is empty(none), it means that the current nexthop is the final nexthop.
	Id *int32 `json:"id,omitempty"`
}

// NewPublishedNexthopEntryInnerViaNh instantiates a new PublishedNexthopEntryInnerViaNh object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedNexthopEntryInnerViaNh() *PublishedNexthopEntryInnerViaNh {
	this := PublishedNexthopEntryInnerViaNh{}
	return &this
}

// NewPublishedNexthopEntryInnerViaNhWithDefaults instantiates a new PublishedNexthopEntryInnerViaNh object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedNexthopEntryInnerViaNhWithDefaults() *PublishedNexthopEntryInnerViaNh {
	this := PublishedNexthopEntryInnerViaNh{}
	return &this
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInnerViaNh) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInnerViaNh) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInnerViaNh) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *PublishedNexthopEntryInnerViaNh) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PublishedNexthopEntryInnerViaNh) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedNexthopEntryInnerViaNh) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PublishedNexthopEntryInnerViaNh) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *PublishedNexthopEntryInnerViaNh) SetId(v int32) {
	o.Id = &v
}

func (o PublishedNexthopEntryInnerViaNh) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedNexthopEntryInnerViaNh) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkInstance) {
		toSerialize["network_instance"] = o.NetworkInstance
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullablePublishedNexthopEntryInnerViaNh struct {
	value *PublishedNexthopEntryInnerViaNh
	isSet bool
}

func (v NullablePublishedNexthopEntryInnerViaNh) Get() *PublishedNexthopEntryInnerViaNh {
	return v.value
}

func (v *NullablePublishedNexthopEntryInnerViaNh) Set(val *PublishedNexthopEntryInnerViaNh) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedNexthopEntryInnerViaNh) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedNexthopEntryInnerViaNh) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedNexthopEntryInnerViaNh(val *PublishedNexthopEntryInnerViaNh) *NullablePublishedNexthopEntryInnerViaNh {
	return &NullablePublishedNexthopEntryInnerViaNh{value: val, isSet: true}
}

func (v NullablePublishedNexthopEntryInnerViaNh) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedNexthopEntryInnerViaNh) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


