/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NexthopRegister type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopRegister{}

// NexthopRegister struct for NexthopRegister
type NexthopRegister struct {
	ClientId *ClientIdentifier `json:"client_id,omitempty"`
	Nexthops []NexthopRegisterItem `json:"nexthops,omitempty"`
}

// NewNexthopRegister instantiates a new NexthopRegister object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopRegister() *NexthopRegister {
	this := NexthopRegister{}
	return &this
}

// NewNexthopRegisterWithDefaults instantiates a new NexthopRegister object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopRegisterWithDefaults() *NexthopRegister {
	this := NexthopRegister{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *NexthopRegister) GetClientId() ClientIdentifier {
	if o == nil || IsNil(o.ClientId) {
		var ret ClientIdentifier
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopRegister) GetClientIdOk() (*ClientIdentifier, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *NexthopRegister) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given ClientIdentifier and assigns it to the ClientId field.
func (o *NexthopRegister) SetClientId(v ClientIdentifier) {
	o.ClientId = &v
}

// GetNexthops returns the Nexthops field value if set, zero value otherwise.
func (o *NexthopRegister) GetNexthops() []NexthopRegisterItem {
	if o == nil || IsNil(o.Nexthops) {
		var ret []NexthopRegisterItem
		return ret
	}
	return o.Nexthops
}

// GetNexthopsOk returns a tuple with the Nexthops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopRegister) GetNexthopsOk() ([]NexthopRegisterItem, bool) {
	if o == nil || IsNil(o.Nexthops) {
		return nil, false
	}
	return o.Nexthops, true
}

// HasNexthops returns a boolean if a field has been set.
func (o *NexthopRegister) HasNexthops() bool {
	if o != nil && !IsNil(o.Nexthops) {
		return true
	}

	return false
}

// SetNexthops gets a reference to the given []NexthopRegisterItem and assigns it to the Nexthops field.
func (o *NexthopRegister) SetNexthops(v []NexthopRegisterItem) {
	o.Nexthops = v
}

func (o NexthopRegister) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopRegister) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.Nexthops) {
		toSerialize["nexthops"] = o.Nexthops
	}
	return toSerialize, nil
}

type NullableNexthopRegister struct {
	value *NexthopRegister
	isSet bool
}

func (v NullableNexthopRegister) Get() *NexthopRegister {
	return v.value
}

func (v *NullableNexthopRegister) Set(val *NexthopRegister) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopRegister) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopRegister) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopRegister(val *NexthopRegister) *NullableNexthopRegister {
	return &NullableNexthopRegister{value: val, isSet: true}
}

func (v NullableNexthopRegister) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopRegister) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


