/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NexthopLabels type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopLabels{}

// NexthopLabels struct for NexthopLabels
type NexthopLabels struct {
	// Nexthop vpn label, when attr = vpn_label of NexthopInformation, the field should be filled, indicates private network routing label;
	VpnLabel *int32 `json:"vpn_label,omitempty"`
	// Nexthop label, When attr = label of NexthopInformation, the field should be filled, indicates public network routing label;
	Label *int32 `json:"label,omitempty"`
}

// NewNexthopLabels instantiates a new NexthopLabels object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopLabels() *NexthopLabels {
	this := NexthopLabels{}
	return &this
}

// NewNexthopLabelsWithDefaults instantiates a new NexthopLabels object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopLabelsWithDefaults() *NexthopLabels {
	this := NexthopLabels{}
	return &this
}

// GetVpnLabel returns the VpnLabel field value if set, zero value otherwise.
func (o *NexthopLabels) GetVpnLabel() int32 {
	if o == nil || IsNil(o.VpnLabel) {
		var ret int32
		return ret
	}
	return *o.VpnLabel
}

// GetVpnLabelOk returns a tuple with the VpnLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopLabels) GetVpnLabelOk() (*int32, bool) {
	if o == nil || IsNil(o.VpnLabel) {
		return nil, false
	}
	return o.VpnLabel, true
}

// HasVpnLabel returns a boolean if a field has been set.
func (o *NexthopLabels) HasVpnLabel() bool {
	if o != nil && !IsNil(o.VpnLabel) {
		return true
	}

	return false
}

// SetVpnLabel gets a reference to the given int32 and assigns it to the VpnLabel field.
func (o *NexthopLabels) SetVpnLabel(v int32) {
	o.VpnLabel = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *NexthopLabels) GetLabel() int32 {
	if o == nil || IsNil(o.Label) {
		var ret int32
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopLabels) GetLabelOk() (*int32, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *NexthopLabels) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given int32 and assigns it to the Label field.
func (o *NexthopLabels) SetLabel(v int32) {
	o.Label = &v
}

func (o NexthopLabels) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopLabels) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VpnLabel) {
		toSerialize["vpn_label"] = o.VpnLabel
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableNexthopLabels struct {
	value *NexthopLabels
	isSet bool
}

func (v NullableNexthopLabels) Get() *NexthopLabels {
	return v.value
}

func (v *NullableNexthopLabels) Set(val *NexthopLabels) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopLabels) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopLabels) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopLabels(val *NexthopLabels) *NullableNexthopLabels {
	return &NullableNexthopLabels{value: val, isSet: true}
}

func (v NullableNexthopLabels) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopLabels) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


