/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Ipv4Prefix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ipv4Prefix{}

// Ipv4Prefix struct for Ipv4Prefix
type Ipv4Prefix struct {
}

// NewIpv4Prefix instantiates a new Ipv4Prefix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpv4Prefix() *Ipv4Prefix {
	this := Ipv4Prefix{}
	return &this
}

// NewIpv4PrefixWithDefaults instantiates a new Ipv4Prefix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpv4PrefixWithDefaults() *Ipv4Prefix {
	this := Ipv4Prefix{}
	return &this
}

func (o Ipv4Prefix) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ipv4Prefix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableIpv4Prefix struct {
	value *Ipv4Prefix
	isSet bool
}

func (v NullableIpv4Prefix) Get() *Ipv4Prefix {
	return v.value
}

func (v *NullableIpv4Prefix) Set(val *Ipv4Prefix) {
	v.value = val
	v.isSet = true
}

func (v NullableIpv4Prefix) IsSet() bool {
	return v.isSet
}

func (v *NullableIpv4Prefix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpv4Prefix(val *Ipv4Prefix) *NullableIpv4Prefix {
	return &NullableIpv4Prefix{value: val, isSet: true}
}

func (v NullableIpv4Prefix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpv4Prefix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


