/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IpPrefix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpPrefix{}

// IpPrefix struct for IpPrefix
type IpPrefix struct {
}

// NewIpPrefix instantiates a new IpPrefix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpPrefix() *IpPrefix {
	this := IpPrefix{}
	return &this
}

// NewIpPrefixWithDefaults instantiates a new IpPrefix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpPrefixWithDefaults() *IpPrefix {
	this := IpPrefix{}
	return &this
}

func (o IpPrefix) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpPrefix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableIpPrefix struct {
	value *IpPrefix
	isSet bool
}

func (v NullableIpPrefix) Get() *IpPrefix {
	return v.value
}

func (v *NullableIpPrefix) Set(val *IpPrefix) {
	v.value = val
	v.isSet = true
}

func (v NullableIpPrefix) IsSet() bool {
	return v.isSet
}

func (v *NullableIpPrefix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpPrefix(val *IpPrefix) *NullableIpPrefix {
	return &NullableIpPrefix{value: val, isSet: true}
}

func (v NullableIpPrefix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpPrefix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


