/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClientUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientUpdate{}

// ClientUpdate struct for ClientUpdate
type ClientUpdate struct {
	ClientId *ClientIdentifier `json:"client_id,omitempty"`
	ConsumerInfo *ConsumerUpdateInfo `json:"consumer_info,omitempty"`
}

// NewClientUpdate instantiates a new ClientUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientUpdate() *ClientUpdate {
	this := ClientUpdate{}
	return &this
}

// NewClientUpdateWithDefaults instantiates a new ClientUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientUpdateWithDefaults() *ClientUpdate {
	this := ClientUpdate{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *ClientUpdate) GetClientId() ClientIdentifier {
	if o == nil || IsNil(o.ClientId) {
		var ret ClientIdentifier
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientUpdate) GetClientIdOk() (*ClientIdentifier, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *ClientUpdate) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given ClientIdentifier and assigns it to the ClientId field.
func (o *ClientUpdate) SetClientId(v ClientIdentifier) {
	o.ClientId = &v
}

// GetConsumerInfo returns the ConsumerInfo field value if set, zero value otherwise.
func (o *ClientUpdate) GetConsumerInfo() ConsumerUpdateInfo {
	if o == nil || IsNil(o.ConsumerInfo) {
		var ret ConsumerUpdateInfo
		return ret
	}
	return *o.ConsumerInfo
}

// GetConsumerInfoOk returns a tuple with the ConsumerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientUpdate) GetConsumerInfoOk() (*ConsumerUpdateInfo, bool) {
	if o == nil || IsNil(o.ConsumerInfo) {
		return nil, false
	}
	return o.ConsumerInfo, true
}

// HasConsumerInfo returns a boolean if a field has been set.
func (o *ClientUpdate) HasConsumerInfo() bool {
	if o != nil && !IsNil(o.ConsumerInfo) {
		return true
	}

	return false
}

// SetConsumerInfo gets a reference to the given ConsumerUpdateInfo and assigns it to the ConsumerInfo field.
func (o *ClientUpdate) SetConsumerInfo(v ConsumerUpdateInfo) {
	o.ConsumerInfo = &v
}

func (o ClientUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ConsumerInfo) {
		toSerialize["consumer_info"] = o.ConsumerInfo
	}
	return toSerialize, nil
}

type NullableClientUpdate struct {
	value *ClientUpdate
	isSet bool
}

func (v NullableClientUpdate) Get() *ClientUpdate {
	return v.value
}

func (v *NullableClientUpdate) Set(val *ClientUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableClientUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableClientUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientUpdate(val *ClientUpdate) *NullableClientUpdate {
	return &NullableClientUpdate{value: val, isSet: true}
}

func (v NullableClientUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


