/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsumerUpdateInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerUpdateInfo{}

// ConsumerUpdateInfo used for consumer client to update its information. route_filters and network_instance_filters are used to specify routes/nexthops that they need be download to consumer. Only routes/nexthops that meet both route_filters and network_instance_filters conditions will be downloaded to consumer.
type ConsumerUpdateInfo struct {
	// for consumer client, used to filter routes as per route type when RIB publish routes to consumer. It shall include all route types that consumer need. Only routes/nexthops that meet both route_filters and network_instance_filters conditions will be downloaded to consumer.
	RouteFilters []RouteType `json:"route_filters,omitempty"`
	// for consumer client, used to filter routes as per network-instance when RIB publish routes to consumer. It shall include all MWs that consumer need. Only routes/nexthops that meet both route_filters and network_instance_filters conditions will be downloaded to consumer.
	NetworkInstanceFilters []string `json:"network_instance_filters,omitempty"`
}

// NewConsumerUpdateInfo instantiates a new ConsumerUpdateInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerUpdateInfo() *ConsumerUpdateInfo {
	this := ConsumerUpdateInfo{}
	return &this
}

// NewConsumerUpdateInfoWithDefaults instantiates a new ConsumerUpdateInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerUpdateInfoWithDefaults() *ConsumerUpdateInfo {
	this := ConsumerUpdateInfo{}
	return &this
}

// GetRouteFilters returns the RouteFilters field value if set, zero value otherwise.
func (o *ConsumerUpdateInfo) GetRouteFilters() []RouteType {
	if o == nil || IsNil(o.RouteFilters) {
		var ret []RouteType
		return ret
	}
	return o.RouteFilters
}

// GetRouteFiltersOk returns a tuple with the RouteFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerUpdateInfo) GetRouteFiltersOk() ([]RouteType, bool) {
	if o == nil || IsNil(o.RouteFilters) {
		return nil, false
	}
	return o.RouteFilters, true
}

// HasRouteFilters returns a boolean if a field has been set.
func (o *ConsumerUpdateInfo) HasRouteFilters() bool {
	if o != nil && !IsNil(o.RouteFilters) {
		return true
	}

	return false
}

// SetRouteFilters gets a reference to the given []RouteType and assigns it to the RouteFilters field.
func (o *ConsumerUpdateInfo) SetRouteFilters(v []RouteType) {
	o.RouteFilters = v
}

// GetNetworkInstanceFilters returns the NetworkInstanceFilters field value if set, zero value otherwise.
func (o *ConsumerUpdateInfo) GetNetworkInstanceFilters() []string {
	if o == nil || IsNil(o.NetworkInstanceFilters) {
		var ret []string
		return ret
	}
	return o.NetworkInstanceFilters
}

// GetNetworkInstanceFiltersOk returns a tuple with the NetworkInstanceFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerUpdateInfo) GetNetworkInstanceFiltersOk() ([]string, bool) {
	if o == nil || IsNil(o.NetworkInstanceFilters) {
		return nil, false
	}
	return o.NetworkInstanceFilters, true
}

// HasNetworkInstanceFilters returns a boolean if a field has been set.
func (o *ConsumerUpdateInfo) HasNetworkInstanceFilters() bool {
	if o != nil && !IsNil(o.NetworkInstanceFilters) {
		return true
	}

	return false
}

// SetNetworkInstanceFilters gets a reference to the given []string and assigns it to the NetworkInstanceFilters field.
func (o *ConsumerUpdateInfo) SetNetworkInstanceFilters(v []string) {
	o.NetworkInstanceFilters = v
}

func (o ConsumerUpdateInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerUpdateInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RouteFilters) {
		toSerialize["route_filters"] = o.RouteFilters
	}
	if !IsNil(o.NetworkInstanceFilters) {
		toSerialize["network_instance_filters"] = o.NetworkInstanceFilters
	}
	return toSerialize, nil
}

type NullableConsumerUpdateInfo struct {
	value *ConsumerUpdateInfo
	isSet bool
}

func (v NullableConsumerUpdateInfo) Get() *ConsumerUpdateInfo {
	return v.value
}

func (v *NullableConsumerUpdateInfo) Set(val *ConsumerUpdateInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerUpdateInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerUpdateInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerUpdateInfo(val *ConsumerUpdateInfo) *NullableConsumerUpdateInfo {
	return &NullableConsumerUpdateInfo{value: val, isSet: true}
}

func (v NullableConsumerUpdateInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerUpdateInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


