/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Redistribution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Redistribution{}

// Redistribution struct for Redistribution
type Redistribution struct {
	ClientId *ClientIdentifier `json:"client_id,omitempty"`
	AddressFamily *string `json:"address_family,omitempty"`
	ProtocolType *RouteType `json:"protocol_type,omitempty"`
	SrcTag *string `json:"srcTag,omitempty"`
	DestProtocolType *string `json:"dest_protocol_type,omitempty"`
	DestTag *string `json:"destTag,omitempty"`
}

// NewRedistribution instantiates a new Redistribution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedistribution() *Redistribution {
	this := Redistribution{}
	return &this
}

// NewRedistributionWithDefaults instantiates a new Redistribution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedistributionWithDefaults() *Redistribution {
	this := Redistribution{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *Redistribution) GetClientId() ClientIdentifier {
	if o == nil || IsNil(o.ClientId) {
		var ret ClientIdentifier
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Redistribution) GetClientIdOk() (*ClientIdentifier, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *Redistribution) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given ClientIdentifier and assigns it to the ClientId field.
func (o *Redistribution) SetClientId(v ClientIdentifier) {
	o.ClientId = &v
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *Redistribution) GetAddressFamily() string {
	if o == nil || IsNil(o.AddressFamily) {
		var ret string
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Redistribution) GetAddressFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.AddressFamily) {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *Redistribution) HasAddressFamily() bool {
	if o != nil && !IsNil(o.AddressFamily) {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given string and assigns it to the AddressFamily field.
func (o *Redistribution) SetAddressFamily(v string) {
	o.AddressFamily = &v
}

// GetProtocolType returns the ProtocolType field value if set, zero value otherwise.
func (o *Redistribution) GetProtocolType() RouteType {
	if o == nil || IsNil(o.ProtocolType) {
		var ret RouteType
		return ret
	}
	return *o.ProtocolType
}

// GetProtocolTypeOk returns a tuple with the ProtocolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Redistribution) GetProtocolTypeOk() (*RouteType, bool) {
	if o == nil || IsNil(o.ProtocolType) {
		return nil, false
	}
	return o.ProtocolType, true
}

// HasProtocolType returns a boolean if a field has been set.
func (o *Redistribution) HasProtocolType() bool {
	if o != nil && !IsNil(o.ProtocolType) {
		return true
	}

	return false
}

// SetProtocolType gets a reference to the given RouteType and assigns it to the ProtocolType field.
func (o *Redistribution) SetProtocolType(v RouteType) {
	o.ProtocolType = &v
}

// GetSrcTag returns the SrcTag field value if set, zero value otherwise.
func (o *Redistribution) GetSrcTag() string {
	if o == nil || IsNil(o.SrcTag) {
		var ret string
		return ret
	}
	return *o.SrcTag
}

// GetSrcTagOk returns a tuple with the SrcTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Redistribution) GetSrcTagOk() (*string, bool) {
	if o == nil || IsNil(o.SrcTag) {
		return nil, false
	}
	return o.SrcTag, true
}

// HasSrcTag returns a boolean if a field has been set.
func (o *Redistribution) HasSrcTag() bool {
	if o != nil && !IsNil(o.SrcTag) {
		return true
	}

	return false
}

// SetSrcTag gets a reference to the given string and assigns it to the SrcTag field.
func (o *Redistribution) SetSrcTag(v string) {
	o.SrcTag = &v
}

// GetDestProtocolType returns the DestProtocolType field value if set, zero value otherwise.
func (o *Redistribution) GetDestProtocolType() string {
	if o == nil || IsNil(o.DestProtocolType) {
		var ret string
		return ret
	}
	return *o.DestProtocolType
}

// GetDestProtocolTypeOk returns a tuple with the DestProtocolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Redistribution) GetDestProtocolTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DestProtocolType) {
		return nil, false
	}
	return o.DestProtocolType, true
}

// HasDestProtocolType returns a boolean if a field has been set.
func (o *Redistribution) HasDestProtocolType() bool {
	if o != nil && !IsNil(o.DestProtocolType) {
		return true
	}

	return false
}

// SetDestProtocolType gets a reference to the given string and assigns it to the DestProtocolType field.
func (o *Redistribution) SetDestProtocolType(v string) {
	o.DestProtocolType = &v
}

// GetDestTag returns the DestTag field value if set, zero value otherwise.
func (o *Redistribution) GetDestTag() string {
	if o == nil || IsNil(o.DestTag) {
		var ret string
		return ret
	}
	return *o.DestTag
}

// GetDestTagOk returns a tuple with the DestTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Redistribution) GetDestTagOk() (*string, bool) {
	if o == nil || IsNil(o.DestTag) {
		return nil, false
	}
	return o.DestTag, true
}

// HasDestTag returns a boolean if a field has been set.
func (o *Redistribution) HasDestTag() bool {
	if o != nil && !IsNil(o.DestTag) {
		return true
	}

	return false
}

// SetDestTag gets a reference to the given string and assigns it to the DestTag field.
func (o *Redistribution) SetDestTag(v string) {
	o.DestTag = &v
}

func (o Redistribution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Redistribution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.AddressFamily) {
		toSerialize["address_family"] = o.AddressFamily
	}
	if !IsNil(o.ProtocolType) {
		toSerialize["protocol_type"] = o.ProtocolType
	}
	if !IsNil(o.SrcTag) {
		toSerialize["srcTag"] = o.SrcTag
	}
	if !IsNil(o.DestProtocolType) {
		toSerialize["dest_protocol_type"] = o.DestProtocolType
	}
	if !IsNil(o.DestTag) {
		toSerialize["destTag"] = o.DestTag
	}
	return toSerialize, nil
}

type NullableRedistribution struct {
	value *Redistribution
	isSet bool
}

func (v NullableRedistribution) Get() *Redistribution {
	return v.value
}

func (v *NullableRedistribution) Set(val *Redistribution) {
	v.value = val
	v.isSet = true
}

func (v NullableRedistribution) IsSet() bool {
	return v.isSet
}

func (v *NullableRedistribution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedistribution(val *Redistribution) *NullableRedistribution {
	return &NullableRedistribution{value: val, isSet: true}
}

func (v NullableRedistribution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedistribution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


