/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrefixNotificationNexthop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrefixNotificationNexthop{}

// PrefixNotificationNexthop struct for PrefixNotificationNexthop
type PrefixNotificationNexthop struct {
	AddressFamily *string `json:"address_family,omitempty"`
	Address *IpAddress `json:"address,omitempty"`
	Metric *int32 `json:"metric,omitempty"`
	ResolvedNetworkInstanceName *string `json:"resolved_network_instance_name,omitempty"`
	ProtocolType *RouteType `json:"protocol_type,omitempty"`
}

// NewPrefixNotificationNexthop instantiates a new PrefixNotificationNexthop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrefixNotificationNexthop() *PrefixNotificationNexthop {
	this := PrefixNotificationNexthop{}
	return &this
}

// NewPrefixNotificationNexthopWithDefaults instantiates a new PrefixNotificationNexthop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrefixNotificationNexthopWithDefaults() *PrefixNotificationNexthop {
	this := PrefixNotificationNexthop{}
	return &this
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *PrefixNotificationNexthop) GetAddressFamily() string {
	if o == nil || IsNil(o.AddressFamily) {
		var ret string
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationNexthop) GetAddressFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.AddressFamily) {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *PrefixNotificationNexthop) HasAddressFamily() bool {
	if o != nil && !IsNil(o.AddressFamily) {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given string and assigns it to the AddressFamily field.
func (o *PrefixNotificationNexthop) SetAddressFamily(v string) {
	o.AddressFamily = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *PrefixNotificationNexthop) GetAddress() IpAddress {
	if o == nil || IsNil(o.Address) {
		var ret IpAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationNexthop) GetAddressOk() (*IpAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *PrefixNotificationNexthop) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given IpAddress and assigns it to the Address field.
func (o *PrefixNotificationNexthop) SetAddress(v IpAddress) {
	o.Address = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *PrefixNotificationNexthop) GetMetric() int32 {
	if o == nil || IsNil(o.Metric) {
		var ret int32
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationNexthop) GetMetricOk() (*int32, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *PrefixNotificationNexthop) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given int32 and assigns it to the Metric field.
func (o *PrefixNotificationNexthop) SetMetric(v int32) {
	o.Metric = &v
}

// GetResolvedNetworkInstanceName returns the ResolvedNetworkInstanceName field value if set, zero value otherwise.
func (o *PrefixNotificationNexthop) GetResolvedNetworkInstanceName() string {
	if o == nil || IsNil(o.ResolvedNetworkInstanceName) {
		var ret string
		return ret
	}
	return *o.ResolvedNetworkInstanceName
}

// GetResolvedNetworkInstanceNameOk returns a tuple with the ResolvedNetworkInstanceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationNexthop) GetResolvedNetworkInstanceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ResolvedNetworkInstanceName) {
		return nil, false
	}
	return o.ResolvedNetworkInstanceName, true
}

// HasResolvedNetworkInstanceName returns a boolean if a field has been set.
func (o *PrefixNotificationNexthop) HasResolvedNetworkInstanceName() bool {
	if o != nil && !IsNil(o.ResolvedNetworkInstanceName) {
		return true
	}

	return false
}

// SetResolvedNetworkInstanceName gets a reference to the given string and assigns it to the ResolvedNetworkInstanceName field.
func (o *PrefixNotificationNexthop) SetResolvedNetworkInstanceName(v string) {
	o.ResolvedNetworkInstanceName = &v
}

// GetProtocolType returns the ProtocolType field value if set, zero value otherwise.
func (o *PrefixNotificationNexthop) GetProtocolType() RouteType {
	if o == nil || IsNil(o.ProtocolType) {
		var ret RouteType
		return ret
	}
	return *o.ProtocolType
}

// GetProtocolTypeOk returns a tuple with the ProtocolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationNexthop) GetProtocolTypeOk() (*RouteType, bool) {
	if o == nil || IsNil(o.ProtocolType) {
		return nil, false
	}
	return o.ProtocolType, true
}

// HasProtocolType returns a boolean if a field has been set.
func (o *PrefixNotificationNexthop) HasProtocolType() bool {
	if o != nil && !IsNil(o.ProtocolType) {
		return true
	}

	return false
}

// SetProtocolType gets a reference to the given RouteType and assigns it to the ProtocolType field.
func (o *PrefixNotificationNexthop) SetProtocolType(v RouteType) {
	o.ProtocolType = &v
}

func (o PrefixNotificationNexthop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrefixNotificationNexthop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressFamily) {
		toSerialize["address_family"] = o.AddressFamily
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.ResolvedNetworkInstanceName) {
		toSerialize["resolved_network_instance_name"] = o.ResolvedNetworkInstanceName
	}
	if !IsNil(o.ProtocolType) {
		toSerialize["protocol_type"] = o.ProtocolType
	}
	return toSerialize, nil
}

type NullablePrefixNotificationNexthop struct {
	value *PrefixNotificationNexthop
	isSet bool
}

func (v NullablePrefixNotificationNexthop) Get() *PrefixNotificationNexthop {
	return v.value
}

func (v *NullablePrefixNotificationNexthop) Set(val *PrefixNotificationNexthop) {
	v.value = val
	v.isSet = true
}

func (v NullablePrefixNotificationNexthop) IsSet() bool {
	return v.isSet
}

func (v *NullablePrefixNotificationNexthop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrefixNotificationNexthop(val *PrefixNotificationNexthop) *NullablePrefixNotificationNexthop {
	return &NullablePrefixNotificationNexthop{value: val, isSet: true}
}

func (v NullablePrefixNotificationNexthop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrefixNotificationNexthop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


