/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// RouteArrayItem - struct for RouteArrayItem
type RouteArrayItem struct {
	AddRouteItem *AddRouteItem
	DeleteRouteItem *DeleteRouteItem
}

// AddRouteItemAsRouteArrayItem is a convenience function that returns AddRouteItem wrapped in RouteArrayItem
func AddRouteItemAsRouteArrayItem(v *AddRouteItem) RouteArrayItem {
	return RouteArrayItem{
		AddRouteItem: v,
	}
}

// DeleteRouteItemAsRouteArrayItem is a convenience function that returns DeleteRouteItem wrapped in RouteArrayItem
func DeleteRouteItemAsRouteArrayItem(v *DeleteRouteItem) RouteArrayItem {
	return RouteArrayItem{
		DeleteRouteItem: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RouteArrayItem) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AddRouteItem
	err = newStrictDecoder(data).Decode(&dst.AddRouteItem)
	if err == nil {
		jsonAddRouteItem, _ := json.Marshal(dst.AddRouteItem)
		if string(jsonAddRouteItem) == "{}" { // empty struct
			dst.AddRouteItem = nil
		} else {
			if err = validator.Validate(dst.AddRouteItem); err != nil {
				dst.AddRouteItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.AddRouteItem = nil
	}

	// try to unmarshal data into DeleteRouteItem
	err = newStrictDecoder(data).Decode(&dst.DeleteRouteItem)
	if err == nil {
		jsonDeleteRouteItem, _ := json.Marshal(dst.DeleteRouteItem)
		if string(jsonDeleteRouteItem) == "{}" { // empty struct
			dst.DeleteRouteItem = nil
		} else {
			if err = validator.Validate(dst.DeleteRouteItem); err != nil {
				dst.DeleteRouteItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeleteRouteItem = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AddRouteItem = nil
		dst.DeleteRouteItem = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RouteArrayItem)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RouteArrayItem)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RouteArrayItem) MarshalJSON() ([]byte, error) {
	if src.AddRouteItem != nil {
		return json.Marshal(&src.AddRouteItem)
	}

	if src.DeleteRouteItem != nil {
		return json.Marshal(&src.DeleteRouteItem)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RouteArrayItem) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AddRouteItem != nil {
		return obj.AddRouteItem
	}

	if obj.DeleteRouteItem != nil {
		return obj.DeleteRouteItem
	}

	// all schemas are nil
	return nil
}

type NullableRouteArrayItem struct {
	value *RouteArrayItem
	isSet bool
}

func (v NullableRouteArrayItem) Get() *RouteArrayItem {
	return v.value
}

func (v *NullableRouteArrayItem) Set(val *RouteArrayItem) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteArrayItem) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteArrayItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteArrayItem(val *RouteArrayItem) *NullableRouteArrayItem {
	return &NullableRouteArrayItem{value: val, isSet: true}
}

func (v NullableRouteArrayItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteArrayItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


