/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsumerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerInfo{}

// ConsumerInfo struct for ConsumerInfo
type ConsumerInfo struct {
	// Unit is second. Indicates how long RIB has not received the client's heartbeat before it considers the client to be dead. If not present, RIB will give a default value.
	KeepaliveTimeout int32 `json:"keepalive_timeout"`
	// for consumer client, used to filter routes as per route type when RIB publish routes to consumer. Only routes/nexthops that meet both route_filters and network_instance_filters conditions will be downloaded to consumer.
	RouteFilters []string `json:"route_filters,omitempty"`
	// for consumer client, used to filter routes as per network-instance when RIB publish routes to consumer. Only routes/nexthops that meet both route_filters and network_instance_filters conditions will be downloaded to consumer.
	NetworkInstanceFilters []string `json:"network_instance_filters,omitempty"`
	// The location will be called to notify EOF information to consumer client. The location will be called to publish routes to consumer client.
	UrlCallback string `json:"url_callback"`
}

type _ConsumerInfo ConsumerInfo

// NewConsumerInfo instantiates a new ConsumerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerInfo(keepaliveTimeout int32, urlCallback string) *ConsumerInfo {
	this := ConsumerInfo{}
	this.KeepaliveTimeout = keepaliveTimeout
	this.UrlCallback = urlCallback
	return &this
}

// NewConsumerInfoWithDefaults instantiates a new ConsumerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerInfoWithDefaults() *ConsumerInfo {
	this := ConsumerInfo{}
	return &this
}

// GetKeepaliveTimeout returns the KeepaliveTimeout field value
func (o *ConsumerInfo) GetKeepaliveTimeout() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.KeepaliveTimeout
}

// GetKeepaliveTimeoutOk returns a tuple with the KeepaliveTimeout field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetKeepaliveTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeepaliveTimeout, true
}

// SetKeepaliveTimeout sets field value
func (o *ConsumerInfo) SetKeepaliveTimeout(v int32) {
	o.KeepaliveTimeout = v
}

// GetRouteFilters returns the RouteFilters field value if set, zero value otherwise.
func (o *ConsumerInfo) GetRouteFilters() []string {
	if o == nil || IsNil(o.RouteFilters) {
		var ret []string
		return ret
	}
	return o.RouteFilters
}

// GetRouteFiltersOk returns a tuple with the RouteFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetRouteFiltersOk() ([]string, bool) {
	if o == nil || IsNil(o.RouteFilters) {
		return nil, false
	}
	return o.RouteFilters, true
}

// HasRouteFilters returns a boolean if a field has been set.
func (o *ConsumerInfo) HasRouteFilters() bool {
	if o != nil && !IsNil(o.RouteFilters) {
		return true
	}

	return false
}

// SetRouteFilters gets a reference to the given []string and assigns it to the RouteFilters field.
func (o *ConsumerInfo) SetRouteFilters(v []string) {
	o.RouteFilters = v
}

// GetNetworkInstanceFilters returns the NetworkInstanceFilters field value if set, zero value otherwise.
func (o *ConsumerInfo) GetNetworkInstanceFilters() []string {
	if o == nil || IsNil(o.NetworkInstanceFilters) {
		var ret []string
		return ret
	}
	return o.NetworkInstanceFilters
}

// GetNetworkInstanceFiltersOk returns a tuple with the NetworkInstanceFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetNetworkInstanceFiltersOk() ([]string, bool) {
	if o == nil || IsNil(o.NetworkInstanceFilters) {
		return nil, false
	}
	return o.NetworkInstanceFilters, true
}

// HasNetworkInstanceFilters returns a boolean if a field has been set.
func (o *ConsumerInfo) HasNetworkInstanceFilters() bool {
	if o != nil && !IsNil(o.NetworkInstanceFilters) {
		return true
	}

	return false
}

// SetNetworkInstanceFilters gets a reference to the given []string and assigns it to the NetworkInstanceFilters field.
func (o *ConsumerInfo) SetNetworkInstanceFilters(v []string) {
	o.NetworkInstanceFilters = v
}

// GetUrlCallback returns the UrlCallback field value
func (o *ConsumerInfo) GetUrlCallback() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlCallback
}

// GetUrlCallbackOk returns a tuple with the UrlCallback field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetUrlCallbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlCallback, true
}

// SetUrlCallback sets field value
func (o *ConsumerInfo) SetUrlCallback(v string) {
	o.UrlCallback = v
}

func (o ConsumerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keepalive_timeout"] = o.KeepaliveTimeout
	if !IsNil(o.RouteFilters) {
		toSerialize["route_filters"] = o.RouteFilters
	}
	if !IsNil(o.NetworkInstanceFilters) {
		toSerialize["network_instance_filters"] = o.NetworkInstanceFilters
	}
	toSerialize["url_callback"] = o.UrlCallback
	return toSerialize, nil
}

func (o *ConsumerInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keepalive_timeout",
		"url_callback",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsumerInfo := _ConsumerInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsumerInfo)

	if err != nil {
		return err
	}

	*o = ConsumerInfo(varConsumerInfo)

	return err
}

type NullableConsumerInfo struct {
	value *ConsumerInfo
	isSet bool
}

func (v NullableConsumerInfo) Get() *ConsumerInfo {
	return v.value
}

func (v *NullableConsumerInfo) Set(val *ConsumerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerInfo(val *ConsumerInfo) *NullableConsumerInfo {
	return &NullableConsumerInfo{value: val, isSet: true}
}

func (v NullableConsumerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


