/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Heartbeat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Heartbeat{}

// Heartbeat struct for Heartbeat
type Heartbeat struct {
	ClientId *ClientIdentifier `json:"client_id,omitempty"`
	// Indicates the role of client
	ClientType *string `json:"client_type,omitempty"`
}

// NewHeartbeat instantiates a new Heartbeat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeartbeat() *Heartbeat {
	this := Heartbeat{}
	return &this
}

// NewHeartbeatWithDefaults instantiates a new Heartbeat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeartbeatWithDefaults() *Heartbeat {
	this := Heartbeat{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *Heartbeat) GetClientId() ClientIdentifier {
	if o == nil || IsNil(o.ClientId) {
		var ret ClientIdentifier
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Heartbeat) GetClientIdOk() (*ClientIdentifier, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *Heartbeat) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given ClientIdentifier and assigns it to the ClientId field.
func (o *Heartbeat) SetClientId(v ClientIdentifier) {
	o.ClientId = &v
}

// GetClientType returns the ClientType field value if set, zero value otherwise.
func (o *Heartbeat) GetClientType() string {
	if o == nil || IsNil(o.ClientType) {
		var ret string
		return ret
	}
	return *o.ClientType
}

// GetClientTypeOk returns a tuple with the ClientType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Heartbeat) GetClientTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ClientType) {
		return nil, false
	}
	return o.ClientType, true
}

// HasClientType returns a boolean if a field has been set.
func (o *Heartbeat) HasClientType() bool {
	if o != nil && !IsNil(o.ClientType) {
		return true
	}

	return false
}

// SetClientType gets a reference to the given string and assigns it to the ClientType field.
func (o *Heartbeat) SetClientType(v string) {
	o.ClientType = &v
}

func (o Heartbeat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Heartbeat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientType) {
		toSerialize["client_type"] = o.ClientType
	}
	return toSerialize, nil
}

type NullableHeartbeat struct {
	value *Heartbeat
	isSet bool
}

func (v NullableHeartbeat) Get() *Heartbeat {
	return v.value
}

func (v *NullableHeartbeat) Set(val *Heartbeat) {
	v.value = val
	v.isSet = true
}

func (v NullableHeartbeat) IsSet() bool {
	return v.isSet
}

func (v *NullableHeartbeat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeartbeat(val *Heartbeat) *NullableHeartbeat {
	return &NullableHeartbeat{value: val, isSet: true}
}

func (v NullableHeartbeat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeartbeat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


