/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrefixNotificationItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrefixNotificationItem{}

// PrefixNotificationItem struct for PrefixNotificationItem
type PrefixNotificationItem struct {
	IsFound *string `json:"is_found,omitempty"`
	NetworkInstance *string `json:"network_instance,omitempty"`
	AddressFamily *string `json:"address_family,omitempty"`
	Prefix *IpPrefix `json:"prefix,omitempty"`
	RetNexthopType *string `json:"ret_nexthop_type,omitempty"`
	// number of ip type's nexthop
	NumIpNexthop *int32 `json:"num_ip_nexthop,omitempty"`
	// number of lsp type's nexthop
	NumLspNexthop *int32 `json:"num_lsp_nexthop,omitempty"`
	// if across network-instance
	InterNetworkInstanceFlag *bool `json:"inter_network_instance_flag,omitempty"`
	MatchedPrefix *IpPrefix `json:"matched_prefix,omitempty"`
	// nexthops of matching prefixes found
	Nexthops []PrefixNotificationNexthop `json:"nexthops,omitempty"`
}

// NewPrefixNotificationItem instantiates a new PrefixNotificationItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrefixNotificationItem() *PrefixNotificationItem {
	this := PrefixNotificationItem{}
	return &this
}

// NewPrefixNotificationItemWithDefaults instantiates a new PrefixNotificationItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrefixNotificationItemWithDefaults() *PrefixNotificationItem {
	this := PrefixNotificationItem{}
	return &this
}

// GetIsFound returns the IsFound field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetIsFound() string {
	if o == nil || IsNil(o.IsFound) {
		var ret string
		return ret
	}
	return *o.IsFound
}

// GetIsFoundOk returns a tuple with the IsFound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetIsFoundOk() (*string, bool) {
	if o == nil || IsNil(o.IsFound) {
		return nil, false
	}
	return o.IsFound, true
}

// HasIsFound returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasIsFound() bool {
	if o != nil && !IsNil(o.IsFound) {
		return true
	}

	return false
}

// SetIsFound gets a reference to the given string and assigns it to the IsFound field.
func (o *PrefixNotificationItem) SetIsFound(v string) {
	o.IsFound = &v
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *PrefixNotificationItem) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetAddressFamily() string {
	if o == nil || IsNil(o.AddressFamily) {
		var ret string
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetAddressFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.AddressFamily) {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasAddressFamily() bool {
	if o != nil && !IsNil(o.AddressFamily) {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given string and assigns it to the AddressFamily field.
func (o *PrefixNotificationItem) SetAddressFamily(v string) {
	o.AddressFamily = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetPrefix() IpPrefix {
	if o == nil || IsNil(o.Prefix) {
		var ret IpPrefix
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetPrefixOk() (*IpPrefix, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given IpPrefix and assigns it to the Prefix field.
func (o *PrefixNotificationItem) SetPrefix(v IpPrefix) {
	o.Prefix = &v
}

// GetRetNexthopType returns the RetNexthopType field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetRetNexthopType() string {
	if o == nil || IsNil(o.RetNexthopType) {
		var ret string
		return ret
	}
	return *o.RetNexthopType
}

// GetRetNexthopTypeOk returns a tuple with the RetNexthopType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetRetNexthopTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RetNexthopType) {
		return nil, false
	}
	return o.RetNexthopType, true
}

// HasRetNexthopType returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasRetNexthopType() bool {
	if o != nil && !IsNil(o.RetNexthopType) {
		return true
	}

	return false
}

// SetRetNexthopType gets a reference to the given string and assigns it to the RetNexthopType field.
func (o *PrefixNotificationItem) SetRetNexthopType(v string) {
	o.RetNexthopType = &v
}

// GetNumIpNexthop returns the NumIpNexthop field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetNumIpNexthop() int32 {
	if o == nil || IsNil(o.NumIpNexthop) {
		var ret int32
		return ret
	}
	return *o.NumIpNexthop
}

// GetNumIpNexthopOk returns a tuple with the NumIpNexthop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetNumIpNexthopOk() (*int32, bool) {
	if o == nil || IsNil(o.NumIpNexthop) {
		return nil, false
	}
	return o.NumIpNexthop, true
}

// HasNumIpNexthop returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasNumIpNexthop() bool {
	if o != nil && !IsNil(o.NumIpNexthop) {
		return true
	}

	return false
}

// SetNumIpNexthop gets a reference to the given int32 and assigns it to the NumIpNexthop field.
func (o *PrefixNotificationItem) SetNumIpNexthop(v int32) {
	o.NumIpNexthop = &v
}

// GetNumLspNexthop returns the NumLspNexthop field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetNumLspNexthop() int32 {
	if o == nil || IsNil(o.NumLspNexthop) {
		var ret int32
		return ret
	}
	return *o.NumLspNexthop
}

// GetNumLspNexthopOk returns a tuple with the NumLspNexthop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetNumLspNexthopOk() (*int32, bool) {
	if o == nil || IsNil(o.NumLspNexthop) {
		return nil, false
	}
	return o.NumLspNexthop, true
}

// HasNumLspNexthop returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasNumLspNexthop() bool {
	if o != nil && !IsNil(o.NumLspNexthop) {
		return true
	}

	return false
}

// SetNumLspNexthop gets a reference to the given int32 and assigns it to the NumLspNexthop field.
func (o *PrefixNotificationItem) SetNumLspNexthop(v int32) {
	o.NumLspNexthop = &v
}

// GetInterNetworkInstanceFlag returns the InterNetworkInstanceFlag field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetInterNetworkInstanceFlag() bool {
	if o == nil || IsNil(o.InterNetworkInstanceFlag) {
		var ret bool
		return ret
	}
	return *o.InterNetworkInstanceFlag
}

// GetInterNetworkInstanceFlagOk returns a tuple with the InterNetworkInstanceFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetInterNetworkInstanceFlagOk() (*bool, bool) {
	if o == nil || IsNil(o.InterNetworkInstanceFlag) {
		return nil, false
	}
	return o.InterNetworkInstanceFlag, true
}

// HasInterNetworkInstanceFlag returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasInterNetworkInstanceFlag() bool {
	if o != nil && !IsNil(o.InterNetworkInstanceFlag) {
		return true
	}

	return false
}

// SetInterNetworkInstanceFlag gets a reference to the given bool and assigns it to the InterNetworkInstanceFlag field.
func (o *PrefixNotificationItem) SetInterNetworkInstanceFlag(v bool) {
	o.InterNetworkInstanceFlag = &v
}

// GetMatchedPrefix returns the MatchedPrefix field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetMatchedPrefix() IpPrefix {
	if o == nil || IsNil(o.MatchedPrefix) {
		var ret IpPrefix
		return ret
	}
	return *o.MatchedPrefix
}

// GetMatchedPrefixOk returns a tuple with the MatchedPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetMatchedPrefixOk() (*IpPrefix, bool) {
	if o == nil || IsNil(o.MatchedPrefix) {
		return nil, false
	}
	return o.MatchedPrefix, true
}

// HasMatchedPrefix returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasMatchedPrefix() bool {
	if o != nil && !IsNil(o.MatchedPrefix) {
		return true
	}

	return false
}

// SetMatchedPrefix gets a reference to the given IpPrefix and assigns it to the MatchedPrefix field.
func (o *PrefixNotificationItem) SetMatchedPrefix(v IpPrefix) {
	o.MatchedPrefix = &v
}

// GetNexthops returns the Nexthops field value if set, zero value otherwise.
func (o *PrefixNotificationItem) GetNexthops() []PrefixNotificationNexthop {
	if o == nil || IsNil(o.Nexthops) {
		var ret []PrefixNotificationNexthop
		return ret
	}
	return o.Nexthops
}

// GetNexthopsOk returns a tuple with the Nexthops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixNotificationItem) GetNexthopsOk() ([]PrefixNotificationNexthop, bool) {
	if o == nil || IsNil(o.Nexthops) {
		return nil, false
	}
	return o.Nexthops, true
}

// HasNexthops returns a boolean if a field has been set.
func (o *PrefixNotificationItem) HasNexthops() bool {
	if o != nil && !IsNil(o.Nexthops) {
		return true
	}

	return false
}

// SetNexthops gets a reference to the given []PrefixNotificationNexthop and assigns it to the Nexthops field.
func (o *PrefixNotificationItem) SetNexthops(v []PrefixNotificationNexthop) {
	o.Nexthops = v
}

func (o PrefixNotificationItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrefixNotificationItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsFound) {
		toSerialize["is_found"] = o.IsFound
	}
	if !IsNil(o.NetworkInstance) {
		toSerialize["network_instance"] = o.NetworkInstance
	}
	if !IsNil(o.AddressFamily) {
		toSerialize["address_family"] = o.AddressFamily
	}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.RetNexthopType) {
		toSerialize["ret_nexthop_type"] = o.RetNexthopType
	}
	if !IsNil(o.NumIpNexthop) {
		toSerialize["num_ip_nexthop"] = o.NumIpNexthop
	}
	if !IsNil(o.NumLspNexthop) {
		toSerialize["num_lsp_nexthop"] = o.NumLspNexthop
	}
	if !IsNil(o.InterNetworkInstanceFlag) {
		toSerialize["inter_network_instance_flag"] = o.InterNetworkInstanceFlag
	}
	if !IsNil(o.MatchedPrefix) {
		toSerialize["matched_prefix"] = o.MatchedPrefix
	}
	if !IsNil(o.Nexthops) {
		toSerialize["nexthops"] = o.Nexthops
	}
	return toSerialize, nil
}

type NullablePrefixNotificationItem struct {
	value *PrefixNotificationItem
	isSet bool
}

func (v NullablePrefixNotificationItem) Get() *PrefixNotificationItem {
	return v.value
}

func (v *NullablePrefixNotificationItem) Set(val *PrefixNotificationItem) {
	v.value = val
	v.isSet = true
}

func (v NullablePrefixNotificationItem) IsSet() bool {
	return v.isSet
}

func (v *NullablePrefixNotificationItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrefixNotificationItem(val *PrefixNotificationItem) *NullablePrefixNotificationItem {
	return &NullablePrefixNotificationItem{value: val, isSet: true}
}

func (v NullablePrefixNotificationItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrefixNotificationItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


