/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NexthopInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopInformation{}

// NexthopInformation struct for NexthopInformation
type NexthopInformation struct {
	// Network instance.
	NetworkInstance string `json:"network_instance"`
	// Address family.
	Afi string `json:"afi"`
	// Attributes of the nexthop of the route.
	Attr []string `json:"attr,omitempty"`
	NhAddr IpAddress `json:"nh_addr"`
	IfInfo *InterfaceInfo `json:"if_info,omitempty"`
	Labels *NexthopLabels `json:"labels,omitempty"`
}

type _NexthopInformation NexthopInformation

// NewNexthopInformation instantiates a new NexthopInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopInformation(networkInstance string, afi string, nhAddr IpAddress) *NexthopInformation {
	this := NexthopInformation{}
	this.NetworkInstance = networkInstance
	this.Afi = afi
	this.NhAddr = nhAddr
	return &this
}

// NewNexthopInformationWithDefaults instantiates a new NexthopInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopInformationWithDefaults() *NexthopInformation {
	this := NexthopInformation{}
	return &this
}

// GetNetworkInstance returns the NetworkInstance field value
func (o *NexthopInformation) GetNetworkInstance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value
// and a boolean to check if the value has been set.
func (o *NexthopInformation) GetNetworkInstanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkInstance, true
}

// SetNetworkInstance sets field value
func (o *NexthopInformation) SetNetworkInstance(v string) {
	o.NetworkInstance = v
}

// GetAfi returns the Afi field value
func (o *NexthopInformation) GetAfi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Afi
}

// GetAfiOk returns a tuple with the Afi field value
// and a boolean to check if the value has been set.
func (o *NexthopInformation) GetAfiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Afi, true
}

// SetAfi sets field value
func (o *NexthopInformation) SetAfi(v string) {
	o.Afi = v
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *NexthopInformation) GetAttr() []string {
	if o == nil || IsNil(o.Attr) {
		var ret []string
		return ret
	}
	return o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopInformation) GetAttrOk() ([]string, bool) {
	if o == nil || IsNil(o.Attr) {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *NexthopInformation) HasAttr() bool {
	if o != nil && !IsNil(o.Attr) {
		return true
	}

	return false
}

// SetAttr gets a reference to the given []string and assigns it to the Attr field.
func (o *NexthopInformation) SetAttr(v []string) {
	o.Attr = v
}

// GetNhAddr returns the NhAddr field value
func (o *NexthopInformation) GetNhAddr() IpAddress {
	if o == nil {
		var ret IpAddress
		return ret
	}

	return o.NhAddr
}

// GetNhAddrOk returns a tuple with the NhAddr field value
// and a boolean to check if the value has been set.
func (o *NexthopInformation) GetNhAddrOk() (*IpAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NhAddr, true
}

// SetNhAddr sets field value
func (o *NexthopInformation) SetNhAddr(v IpAddress) {
	o.NhAddr = v
}

// GetIfInfo returns the IfInfo field value if set, zero value otherwise.
func (o *NexthopInformation) GetIfInfo() InterfaceInfo {
	if o == nil || IsNil(o.IfInfo) {
		var ret InterfaceInfo
		return ret
	}
	return *o.IfInfo
}

// GetIfInfoOk returns a tuple with the IfInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopInformation) GetIfInfoOk() (*InterfaceInfo, bool) {
	if o == nil || IsNil(o.IfInfo) {
		return nil, false
	}
	return o.IfInfo, true
}

// HasIfInfo returns a boolean if a field has been set.
func (o *NexthopInformation) HasIfInfo() bool {
	if o != nil && !IsNil(o.IfInfo) {
		return true
	}

	return false
}

// SetIfInfo gets a reference to the given InterfaceInfo and assigns it to the IfInfo field.
func (o *NexthopInformation) SetIfInfo(v InterfaceInfo) {
	o.IfInfo = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *NexthopInformation) GetLabels() NexthopLabels {
	if o == nil || IsNil(o.Labels) {
		var ret NexthopLabels
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopInformation) GetLabelsOk() (*NexthopLabels, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *NexthopInformation) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given NexthopLabels and assigns it to the Labels field.
func (o *NexthopInformation) SetLabels(v NexthopLabels) {
	o.Labels = &v
}

func (o NexthopInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network_instance"] = o.NetworkInstance
	toSerialize["afi"] = o.Afi
	if !IsNil(o.Attr) {
		toSerialize["attr"] = o.Attr
	}
	toSerialize["nh_addr"] = o.NhAddr
	if !IsNil(o.IfInfo) {
		toSerialize["if_info"] = o.IfInfo
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *NexthopInformation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network_instance",
		"afi",
		"nh_addr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNexthopInformation := _NexthopInformation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNexthopInformation)

	if err != nil {
		return err
	}

	*o = NexthopInformation(varNexthopInformation)

	return err
}

type NullableNexthopInformation struct {
	value *NexthopInformation
	isSet bool
}

func (v NullableNexthopInformation) Get() *NexthopInformation {
	return v.value
}

func (v *NullableNexthopInformation) Set(val *NexthopInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopInformation(val *NexthopInformation) *NullableNexthopInformation {
	return &NullableNexthopInformation{value: val, isSet: true}
}

func (v NullableNexthopInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


