/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RouteEOFToConsumer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouteEOFToConsumer{}

// RouteEOFToConsumer After RIB publish all its existed routes/nexthops to consumer, RIB will send route EOF to consumer.
type RouteEOFToConsumer struct {
	Type *string `json:"type,omitempty"`
}

// NewRouteEOFToConsumer instantiates a new RouteEOFToConsumer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouteEOFToConsumer() *RouteEOFToConsumer {
	this := RouteEOFToConsumer{}
	return &this
}

// NewRouteEOFToConsumerWithDefaults instantiates a new RouteEOFToConsumer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteEOFToConsumerWithDefaults() *RouteEOFToConsumer {
	this := RouteEOFToConsumer{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RouteEOFToConsumer) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteEOFToConsumer) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RouteEOFToConsumer) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RouteEOFToConsumer) SetType(v string) {
	o.Type = &v
}

func (o RouteEOFToConsumer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouteEOFToConsumer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableRouteEOFToConsumer struct {
	value *RouteEOFToConsumer
	isSet bool
}

func (v NullableRouteEOFToConsumer) Get() *RouteEOFToConsumer {
	return v.value
}

func (v *NullableRouteEOFToConsumer) Set(val *RouteEOFToConsumer) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteEOFToConsumer) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteEOFToConsumer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteEOFToConsumer(val *RouteEOFToConsumer) *NullableRouteEOFToConsumer {
	return &NullableRouteEOFToConsumer{value: val, isSet: true}
}

func (v NullableRouteEOFToConsumer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteEOFToConsumer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


