/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Ipv6Address type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ipv6Address{}

// Ipv6Address struct for Ipv6Address
type Ipv6Address struct {
}

// NewIpv6Address instantiates a new Ipv6Address object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpv6Address() *Ipv6Address {
	this := Ipv6Address{}
	return &this
}

// NewIpv6AddressWithDefaults instantiates a new Ipv6Address object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpv6AddressWithDefaults() *Ipv6Address {
	this := Ipv6Address{}
	return &this
}

func (o Ipv6Address) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ipv6Address) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableIpv6Address struct {
	value *Ipv6Address
	isSet bool
}

func (v NullableIpv6Address) Get() *Ipv6Address {
	return v.value
}

func (v *NullableIpv6Address) Set(val *Ipv6Address) {
	v.value = val
	v.isSet = true
}

func (v NullableIpv6Address) IsSet() bool {
	return v.isSet
}

func (v *NullableIpv6Address) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpv6Address(val *Ipv6Address) *NullableIpv6Address {
	return &NullableIpv6Address{value: val, isSet: true}
}

func (v NullableIpv6Address) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpv6Address) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


