/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NexthopRegisterItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopRegisterItem{}

// NexthopRegisterItem struct for NexthopRegisterItem
type NexthopRegisterItem struct {
	AddressFamily *string `json:"address_family,omitempty"`
	Address *IpAddress `json:"address,omitempty"`
}

// NewNexthopRegisterItem instantiates a new NexthopRegisterItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopRegisterItem() *NexthopRegisterItem {
	this := NexthopRegisterItem{}
	return &this
}

// NewNexthopRegisterItemWithDefaults instantiates a new NexthopRegisterItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopRegisterItemWithDefaults() *NexthopRegisterItem {
	this := NexthopRegisterItem{}
	return &this
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *NexthopRegisterItem) GetAddressFamily() string {
	if o == nil || IsNil(o.AddressFamily) {
		var ret string
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopRegisterItem) GetAddressFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.AddressFamily) {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *NexthopRegisterItem) HasAddressFamily() bool {
	if o != nil && !IsNil(o.AddressFamily) {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given string and assigns it to the AddressFamily field.
func (o *NexthopRegisterItem) SetAddressFamily(v string) {
	o.AddressFamily = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *NexthopRegisterItem) GetAddress() IpAddress {
	if o == nil || IsNil(o.Address) {
		var ret IpAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopRegisterItem) GetAddressOk() (*IpAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *NexthopRegisterItem) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given IpAddress and assigns it to the Address field.
func (o *NexthopRegisterItem) SetAddress(v IpAddress) {
	o.Address = &v
}

func (o NexthopRegisterItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopRegisterItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressFamily) {
		toSerialize["address_family"] = o.AddressFamily
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableNexthopRegisterItem struct {
	value *NexthopRegisterItem
	isSet bool
}

func (v NullableNexthopRegisterItem) Get() *NexthopRegisterItem {
	return v.value
}

func (v *NullableNexthopRegisterItem) Set(val *NexthopRegisterItem) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopRegisterItem) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopRegisterItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopRegisterItem(val *NexthopRegisterItem) *NullableNexthopRegisterItem {
	return &NullableNexthopRegisterItem{value: val, isSet: true}
}

func (v NullableNexthopRegisterItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopRegisterItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


