/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NotifyInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotifyInformation{}

// NotifyInformation struct for NotifyInformation
type NotifyInformation struct {
	ClientId *ClientIdentifier `json:"client_id,omitempty"`
	Msg *NotifyInformationMsg `json:"msg,omitempty"`
}

// NewNotifyInformation instantiates a new NotifyInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotifyInformation() *NotifyInformation {
	this := NotifyInformation{}
	return &this
}

// NewNotifyInformationWithDefaults instantiates a new NotifyInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotifyInformationWithDefaults() *NotifyInformation {
	this := NotifyInformation{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *NotifyInformation) GetClientId() ClientIdentifier {
	if o == nil || IsNil(o.ClientId) {
		var ret ClientIdentifier
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotifyInformation) GetClientIdOk() (*ClientIdentifier, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *NotifyInformation) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given ClientIdentifier and assigns it to the ClientId field.
func (o *NotifyInformation) SetClientId(v ClientIdentifier) {
	o.ClientId = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *NotifyInformation) GetMsg() NotifyInformationMsg {
	if o == nil || IsNil(o.Msg) {
		var ret NotifyInformationMsg
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotifyInformation) GetMsgOk() (*NotifyInformationMsg, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *NotifyInformation) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given NotifyInformationMsg and assigns it to the Msg field.
func (o *NotifyInformation) SetMsg(v NotifyInformationMsg) {
	o.Msg = &v
}

func (o NotifyInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotifyInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	return toSerialize, nil
}

type NullableNotifyInformation struct {
	value *NotifyInformation
	isSet bool
}

func (v NullableNotifyInformation) Get() *NotifyInformation {
	return v.value
}

func (v *NullableNotifyInformation) Set(val *NotifyInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableNotifyInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableNotifyInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotifyInformation(val *NotifyInformation) *NullableNotifyInformation {
	return &NullableNotifyInformation{value: val, isSet: true}
}

func (v NullableNotifyInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotifyInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


