/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Client type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Client{}

// Client struct for Client
type Client struct {
	ClientId *ClientIdentifier `json:"client_id,omitempty"`
	ProducerInfo *ProducerInfo `json:"producer_info,omitempty"`
	ConsumerInfo *ConsumerInfo `json:"consumer_info,omitempty"`
}

// NewClient instantiates a new Client object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClient() *Client {
	this := Client{}
	return &this
}

// NewClientWithDefaults instantiates a new Client object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientWithDefaults() *Client {
	this := Client{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *Client) GetClientId() ClientIdentifier {
	if o == nil || IsNil(o.ClientId) {
		var ret ClientIdentifier
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Client) GetClientIdOk() (*ClientIdentifier, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *Client) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given ClientIdentifier and assigns it to the ClientId field.
func (o *Client) SetClientId(v ClientIdentifier) {
	o.ClientId = &v
}

// GetProducerInfo returns the ProducerInfo field value if set, zero value otherwise.
func (o *Client) GetProducerInfo() ProducerInfo {
	if o == nil || IsNil(o.ProducerInfo) {
		var ret ProducerInfo
		return ret
	}
	return *o.ProducerInfo
}

// GetProducerInfoOk returns a tuple with the ProducerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Client) GetProducerInfoOk() (*ProducerInfo, bool) {
	if o == nil || IsNil(o.ProducerInfo) {
		return nil, false
	}
	return o.ProducerInfo, true
}

// HasProducerInfo returns a boolean if a field has been set.
func (o *Client) HasProducerInfo() bool {
	if o != nil && !IsNil(o.ProducerInfo) {
		return true
	}

	return false
}

// SetProducerInfo gets a reference to the given ProducerInfo and assigns it to the ProducerInfo field.
func (o *Client) SetProducerInfo(v ProducerInfo) {
	o.ProducerInfo = &v
}

// GetConsumerInfo returns the ConsumerInfo field value if set, zero value otherwise.
func (o *Client) GetConsumerInfo() ConsumerInfo {
	if o == nil || IsNil(o.ConsumerInfo) {
		var ret ConsumerInfo
		return ret
	}
	return *o.ConsumerInfo
}

// GetConsumerInfoOk returns a tuple with the ConsumerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Client) GetConsumerInfoOk() (*ConsumerInfo, bool) {
	if o == nil || IsNil(o.ConsumerInfo) {
		return nil, false
	}
	return o.ConsumerInfo, true
}

// HasConsumerInfo returns a boolean if a field has been set.
func (o *Client) HasConsumerInfo() bool {
	if o != nil && !IsNil(o.ConsumerInfo) {
		return true
	}

	return false
}

// SetConsumerInfo gets a reference to the given ConsumerInfo and assigns it to the ConsumerInfo field.
func (o *Client) SetConsumerInfo(v ConsumerInfo) {
	o.ConsumerInfo = &v
}

func (o Client) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Client) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ProducerInfo) {
		toSerialize["producer_info"] = o.ProducerInfo
	}
	if !IsNil(o.ConsumerInfo) {
		toSerialize["consumer_info"] = o.ConsumerInfo
	}
	return toSerialize, nil
}

type NullableClient struct {
	value *Client
	isSet bool
}

func (v NullableClient) Get() *Client {
	return v.value
}

func (v *NullableClient) Set(val *Client) {
	v.value = val
	v.isSet = true
}

func (v NullableClient) IsSet() bool {
	return v.isSet
}

func (v *NullableClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClient(val *Client) *NullableClient {
	return &NullableClient{value: val, isSet: true}
}

func (v NullableClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


