/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RouteType route or protocol type.
type RouteType string

// List of route_type
const (
	STATIC RouteType = "static"
	BGP RouteType = "bgp"
	CONNECT RouteType = "connect"
)

// All allowed values of RouteType enum
var AllowedRouteTypeEnumValues = []RouteType{
	"static",
	"bgp",
	"connect",
}

func (v *RouteType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RouteType(value)
	for _, existing := range AllowedRouteTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RouteType", value)
}

// NewRouteTypeFromValue returns a pointer to a valid RouteType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRouteTypeFromValue(v string) (*RouteType, error) {
	ev := RouteType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RouteType: valid values are %v", v, AllowedRouteTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RouteType) IsValid() bool {
	for _, existing := range AllowedRouteTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to route_type value
func (v RouteType) Ptr() *RouteType {
	return &v
}

type NullableRouteType struct {
	value *RouteType
	isSet bool
}

func (v NullableRouteType) Get() *RouteType {
	return v.value
}

func (v *NullableRouteType) Set(val *RouteType) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteType) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteType(val *RouteType) *NullableRouteType {
	return &NullableRouteType{value: val, isSet: true}
}

func (v NullableRouteType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

