/*
Routing Information Base API

API for Routing Information Base.

API version: 1.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RedistributionNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedistributionNotification{}

// RedistributionNotification struct for RedistributionNotification
type RedistributionNotification struct {
	Type *string `json:"type,omitempty"`
	Header *RedistributionNotificationHeader `json:"header,omitempty"`
	Routes []RedistributionNotificationRoute `json:"routes,omitempty"`
}

// NewRedistributionNotification instantiates a new RedistributionNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedistributionNotification() *RedistributionNotification {
	this := RedistributionNotification{}
	return &this
}

// NewRedistributionNotificationWithDefaults instantiates a new RedistributionNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedistributionNotificationWithDefaults() *RedistributionNotification {
	this := RedistributionNotification{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RedistributionNotification) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedistributionNotification) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RedistributionNotification) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RedistributionNotification) SetType(v string) {
	o.Type = &v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *RedistributionNotification) GetHeader() RedistributionNotificationHeader {
	if o == nil || IsNil(o.Header) {
		var ret RedistributionNotificationHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedistributionNotification) GetHeaderOk() (*RedistributionNotificationHeader, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *RedistributionNotification) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given RedistributionNotificationHeader and assigns it to the Header field.
func (o *RedistributionNotification) SetHeader(v RedistributionNotificationHeader) {
	o.Header = &v
}

// GetRoutes returns the Routes field value if set, zero value otherwise.
func (o *RedistributionNotification) GetRoutes() []RedistributionNotificationRoute {
	if o == nil || IsNil(o.Routes) {
		var ret []RedistributionNotificationRoute
		return ret
	}
	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedistributionNotification) GetRoutesOk() ([]RedistributionNotificationRoute, bool) {
	if o == nil || IsNil(o.Routes) {
		return nil, false
	}
	return o.Routes, true
}

// HasRoutes returns a boolean if a field has been set.
func (o *RedistributionNotification) HasRoutes() bool {
	if o != nil && !IsNil(o.Routes) {
		return true
	}

	return false
}

// SetRoutes gets a reference to the given []RedistributionNotificationRoute and assigns it to the Routes field.
func (o *RedistributionNotification) SetRoutes(v []RedistributionNotificationRoute) {
	o.Routes = v
}

func (o RedistributionNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedistributionNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.Routes) {
		toSerialize["routes"] = o.Routes
	}
	return toSerialize, nil
}

type NullableRedistributionNotification struct {
	value *RedistributionNotification
	isSet bool
}

func (v NullableRedistributionNotification) Get() *RedistributionNotification {
	return v.value
}

func (v *NullableRedistributionNotification) Set(val *RedistributionNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableRedistributionNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableRedistributionNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedistributionNotification(val *RedistributionNotification) *NullableRedistributionNotification {
	return &NullableRedistributionNotification{value: val, isSet: true}
}

func (v NullableRedistributionNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedistributionNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


