/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// NexthopsAPIService NexthopsAPI service
type NexthopsAPIService service

type ApiDeregisterNexthopRequest struct {
	ctx context.Context
	ApiService *NexthopsAPIService
	networkInstanceName string
	producerId string
	nexthopRegister *NexthopRegister
}

func (r ApiDeregisterNexthopRequest) NexthopRegister(nexthopRegister NexthopRegister) ApiDeregisterNexthopRequest {
	r.nexthopRegister = &nexthopRegister
	return r
}

func (r ApiDeregisterNexthopRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeregisterNexthopExecute(r)
}

/*
DeregisterNexthop Method for DeregisterNexthop

deregister nexthop.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param networkInstanceName networkInstance to which the nexthop belongs to.
 @param producerId producer name, please refer to the clientIdentifier provided by producer when it register to RIB.
 @return ApiDeregisterNexthopRequest
*/
func (a *NexthopsAPIService) DeregisterNexthop(ctx context.Context, networkInstanceName string, producerId string) ApiDeregisterNexthopRequest {
	return ApiDeregisterNexthopRequest{
		ApiService: a,
		ctx: ctx,
		networkInstanceName: networkInstanceName,
		producerId: producerId,
	}
}

// Execute executes the request
func (a *NexthopsAPIService) DeregisterNexthopExecute(r ApiDeregisterNexthopRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexthopsAPIService.DeregisterNexthop")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/network-instances/{networkInstanceName}/producers/{producerId}/nexthops"
	localVarPath = strings.Replace(localVarPath, "{"+"networkInstanceName"+"}", url.PathEscape(parameterValueToString(r.networkInstanceName, "networkInstanceName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"producerId"+"}", url.PathEscape(parameterValueToString(r.producerId, "producerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.nexthopRegister == nil {
		return nil, reportError("nexthopRegister is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nexthopRegister
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiReceiveNexthopRegistrationEOFRequest struct {
	ctx context.Context
	ApiService *NexthopsAPIService
	networkInstanceName string
	producerId string
}

func (r ApiReceiveNexthopRegistrationEOFRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReceiveNexthopRegistrationEOFExecute(r)
}

/*
ReceiveNexthopRegistrationEOF Method for ReceiveNexthopRegistrationEOF

During startup, producer client should call this API to send nexthop registration EOF to RIB after it registered all its nexthop with RIB. RIB need know if producer client finished register nexthop with RIB.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param networkInstanceName networkInstance to which the EOF belongs to.
 @param producerId producer name, please refer to the clientIdentifier provided by producer when it register to RIB.
 @return ApiReceiveNexthopRegistrationEOFRequest
*/
func (a *NexthopsAPIService) ReceiveNexthopRegistrationEOF(ctx context.Context, networkInstanceName string, producerId string) ApiReceiveNexthopRegistrationEOFRequest {
	return ApiReceiveNexthopRegistrationEOFRequest{
		ApiService: a,
		ctx: ctx,
		networkInstanceName: networkInstanceName,
		producerId: producerId,
	}
}

// Execute executes the request
func (a *NexthopsAPIService) ReceiveNexthopRegistrationEOFExecute(r ApiReceiveNexthopRegistrationEOFRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexthopsAPIService.ReceiveNexthopRegistrationEOF")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/network-instances/{networkInstanceName}/producers/{producerId}/nexthop-reg-eof"
	localVarPath = strings.Replace(localVarPath, "{"+"networkInstanceName"+"}", url.PathEscape(parameterValueToString(r.networkInstanceName, "networkInstanceName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"producerId"+"}", url.PathEscape(parameterValueToString(r.producerId, "producerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiRegisterNexthopRequest struct {
	ctx context.Context
	ApiService *NexthopsAPIService
	networkInstanceName string
	producerId string
	nexthopRegister *NexthopRegister
}

func (r ApiRegisterNexthopRequest) NexthopRegister(nexthopRegister NexthopRegister) ApiRegisterNexthopRequest {
	r.nexthopRegister = &nexthopRegister
	return r
}

func (r ApiRegisterNexthopRequest) Execute() (*http.Response, error) {
	return r.ApiService.RegisterNexthopExecute(r)
}

/*
RegisterNexthop Method for RegisterNexthop

Register nexthop in RIB. if producer client wants to be aware of the change for a nexthop, it can register the nexthop to RIB. Thus RIB can notify producer client once the nexthop changed.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param networkInstanceName networkInstance to which the nexthop belongs to.
 @param producerId producer name, please refer to the clientIdentifier provided by producer when it register to RIB.
 @return ApiRegisterNexthopRequest
*/
func (a *NexthopsAPIService) RegisterNexthop(ctx context.Context, networkInstanceName string, producerId string) ApiRegisterNexthopRequest {
	return ApiRegisterNexthopRequest{
		ApiService: a,
		ctx: ctx,
		networkInstanceName: networkInstanceName,
		producerId: producerId,
	}
}

// Execute executes the request
func (a *NexthopsAPIService) RegisterNexthopExecute(r ApiRegisterNexthopRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NexthopsAPIService.RegisterNexthop")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/network-instances/{networkInstanceName}/producers/{producerId}/nexthops"
	localVarPath = strings.Replace(localVarPath, "{"+"networkInstanceName"+"}", url.PathEscape(parameterValueToString(r.networkInstanceName, "networkInstanceName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"producerId"+"}", url.PathEscape(parameterValueToString(r.producerId, "producerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.nexthopRegister == nil {
		return nil, reportError("nexthopRegister is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nexthopRegister
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
