/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// PrefixesAPIService PrefixesAPI service
type PrefixesAPIService service

type ApiDeregisterPrefixRequest struct {
	ctx context.Context
	ApiService *PrefixesAPIService
	networkInstanceName string
	producerId string
	prefixRegister *PrefixRegister
}

func (r ApiDeregisterPrefixRequest) PrefixRegister(prefixRegister PrefixRegister) ApiDeregisterPrefixRequest {
	r.prefixRegister = &prefixRegister
	return r
}

func (r ApiDeregisterPrefixRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeregisterPrefixExecute(r)
}

/*
DeregisterPrefix Method for DeregisterPrefix

deregister a prefix.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param networkInstanceName networkInstance to which the prefix belongs to.
 @param producerId producer name, please refer to the clientIdentifier provided by producer when it register to RIB.
 @return ApiDeregisterPrefixRequest
*/
func (a *PrefixesAPIService) DeregisterPrefix(ctx context.Context, networkInstanceName string, producerId string) ApiDeregisterPrefixRequest {
	return ApiDeregisterPrefixRequest{
		ApiService: a,
		ctx: ctx,
		networkInstanceName: networkInstanceName,
		producerId: producerId,
	}
}

// Execute executes the request
func (a *PrefixesAPIService) DeregisterPrefixExecute(r ApiDeregisterPrefixRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PrefixesAPIService.DeregisterPrefix")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/network-instances/{networkInstanceName}/producers/{producerId}/prefixes"
	localVarPath = strings.Replace(localVarPath, "{"+"networkInstanceName"+"}", url.PathEscape(parameterValueToString(r.networkInstanceName, "networkInstanceName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"producerId"+"}", url.PathEscape(parameterValueToString(r.producerId, "producerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.prefixRegister == nil {
		return nil, reportError("prefixRegister is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.prefixRegister
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiReceivePrefixRegistrationEOFRequest struct {
	ctx context.Context
	ApiService *PrefixesAPIService
	networkInstanceName string
	producerId string
}

func (r ApiReceivePrefixRegistrationEOFRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReceivePrefixRegistrationEOFExecute(r)
}

/*
ReceivePrefixRegistrationEOF Method for ReceivePrefixRegistrationEOF

During startup, producer client should call this API to send prefix registration EOF to RIB after it registered all its prefix with RIB. RIB need know if producer client finished register prefix with RIB.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param networkInstanceName networkInstance to which the EOF belongs to.
 @param producerId producer name, please refer to the clientIdentifier provided by producer when it register to RIB.
 @return ApiReceivePrefixRegistrationEOFRequest
*/
func (a *PrefixesAPIService) ReceivePrefixRegistrationEOF(ctx context.Context, networkInstanceName string, producerId string) ApiReceivePrefixRegistrationEOFRequest {
	return ApiReceivePrefixRegistrationEOFRequest{
		ApiService: a,
		ctx: ctx,
		networkInstanceName: networkInstanceName,
		producerId: producerId,
	}
}

// Execute executes the request
func (a *PrefixesAPIService) ReceivePrefixRegistrationEOFExecute(r ApiReceivePrefixRegistrationEOFRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PrefixesAPIService.ReceivePrefixRegistrationEOF")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/network-instances/{networkInstanceName}/producers/{producerId}/prefix-reg-eof"
	localVarPath = strings.Replace(localVarPath, "{"+"networkInstanceName"+"}", url.PathEscape(parameterValueToString(r.networkInstanceName, "networkInstanceName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"producerId"+"}", url.PathEscape(parameterValueToString(r.producerId, "producerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiRegisterPrefixRequest struct {
	ctx context.Context
	ApiService *PrefixesAPIService
	networkInstanceName string
	producerId string
	prefixRegister *PrefixRegister
}

func (r ApiRegisterPrefixRequest) PrefixRegister(prefixRegister PrefixRegister) ApiRegisterPrefixRequest {
	r.prefixRegister = &prefixRegister
	return r
}

func (r ApiRegisterPrefixRequest) Execute() (*http.Response, error) {
	return r.ApiService.RegisterPrefixExecute(r)
}

/*
RegisterPrefix Method for RegisterPrefix

Register a prefix. if producer client want to be aware of the change for a prefix, it can register the prefix to RIB. Thus RIB can notify producer client once the prefix changed.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param networkInstanceName networkInstance to which the prefix belongs to.
 @param producerId producer name, please refer to the clientIdentifier provided by producer when it register to RIB.
 @return ApiRegisterPrefixRequest
*/
func (a *PrefixesAPIService) RegisterPrefix(ctx context.Context, networkInstanceName string, producerId string) ApiRegisterPrefixRequest {
	return ApiRegisterPrefixRequest{
		ApiService: a,
		ctx: ctx,
		networkInstanceName: networkInstanceName,
		producerId: producerId,
	}
}

// Execute executes the request
func (a *PrefixesAPIService) RegisterPrefixExecute(r ApiRegisterPrefixRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PrefixesAPIService.RegisterPrefix")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/network-instances/{networkInstanceName}/producers/{producerId}/prefixes"
	localVarPath = strings.Replace(localVarPath, "{"+"networkInstanceName"+"}", url.PathEscape(parameterValueToString(r.networkInstanceName, "networkInstanceName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"producerId"+"}", url.PathEscape(parameterValueToString(r.producerId, "producerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.prefixRegister == nil {
		return nil, reportError("prefixRegister is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.prefixRegister
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
