/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsumerNexthopsNotificationItemEntryInnerViaNexthop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerNexthopsNotificationItemEntryInnerViaNexthop{}

// ConsumerNexthopsNotificationItemEntryInnerViaNexthop Via nexthop identifer which composed by nexthop networkInstance and an optional nexthop id.
type ConsumerNexthopsNotificationItemEntryInnerViaNexthop struct {
	// The networkInstance which via nexthop belongs to.
	NetworkInstance string `json:"networkInstance"`
	// Nexthop id, identify a nexthop. Optional, if \"id\" is empty(none), it means that the current nexthop is the final nexthop.
	Id *int32 `json:"id,omitempty"`
}

type _ConsumerNexthopsNotificationItemEntryInnerViaNexthop ConsumerNexthopsNotificationItemEntryInnerViaNexthop

// NewConsumerNexthopsNotificationItemEntryInnerViaNexthop instantiates a new ConsumerNexthopsNotificationItemEntryInnerViaNexthop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerNexthopsNotificationItemEntryInnerViaNexthop(networkInstance string) *ConsumerNexthopsNotificationItemEntryInnerViaNexthop {
	this := ConsumerNexthopsNotificationItemEntryInnerViaNexthop{}
	this.NetworkInstance = networkInstance
	return &this
}

// NewConsumerNexthopsNotificationItemEntryInnerViaNexthopWithDefaults instantiates a new ConsumerNexthopsNotificationItemEntryInnerViaNexthop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerNexthopsNotificationItemEntryInnerViaNexthopWithDefaults() *ConsumerNexthopsNotificationItemEntryInnerViaNexthop {
	this := ConsumerNexthopsNotificationItemEntryInnerViaNexthop{}
	return &this
}

// GetNetworkInstance returns the NetworkInstance field value
func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) GetNetworkInstance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) GetNetworkInstanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkInstance, true
}

// SetNetworkInstance sets field value
func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) SetNetworkInstance(v string) {
	o.NetworkInstance = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) SetId(v int32) {
	o.Id = &v
}

func (o ConsumerNexthopsNotificationItemEntryInnerViaNexthop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerNexthopsNotificationItemEntryInnerViaNexthop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["networkInstance"] = o.NetworkInstance
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

func (o *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"networkInstance",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsumerNexthopsNotificationItemEntryInnerViaNexthop := _ConsumerNexthopsNotificationItemEntryInnerViaNexthop{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsumerNexthopsNotificationItemEntryInnerViaNexthop)

	if err != nil {
		return err
	}

	*o = ConsumerNexthopsNotificationItemEntryInnerViaNexthop(varConsumerNexthopsNotificationItemEntryInnerViaNexthop)

	return err
}

type NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop struct {
	value *ConsumerNexthopsNotificationItemEntryInnerViaNexthop
	isSet bool
}

func (v NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop) Get() *ConsumerNexthopsNotificationItemEntryInnerViaNexthop {
	return v.value
}

func (v *NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop) Set(val *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerNexthopsNotificationItemEntryInnerViaNexthop(val *ConsumerNexthopsNotificationItemEntryInnerViaNexthop) *NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop {
	return &NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop{value: val, isSet: true}
}

func (v NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerNexthopsNotificationItemEntryInnerViaNexthop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


