/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsumerNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerNotification{}

// ConsumerNotification struct for ConsumerNotification
type ConsumerNotification struct {
	// Indicates client name, for either Producer or Consumer. For route-engine, client name is like {cre-pod-name} + {static/bgp/ifm}, for data-plane, client name is like {dp-pod-name}, for client that is service, client name is like {service-name}.
	ConsumerId *string `json:"consumerId,omitempty"`
	Msg *ConsumerNotificationMsg `json:"msg,omitempty"`
}

// NewConsumerNotification instantiates a new ConsumerNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerNotification() *ConsumerNotification {
	this := ConsumerNotification{}
	return &this
}

// NewConsumerNotificationWithDefaults instantiates a new ConsumerNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerNotificationWithDefaults() *ConsumerNotification {
	this := ConsumerNotification{}
	return &this
}

// GetConsumerId returns the ConsumerId field value if set, zero value otherwise.
func (o *ConsumerNotification) GetConsumerId() string {
	if o == nil || IsNil(o.ConsumerId) {
		var ret string
		return ret
	}
	return *o.ConsumerId
}

// GetConsumerIdOk returns a tuple with the ConsumerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNotification) GetConsumerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConsumerId) {
		return nil, false
	}
	return o.ConsumerId, true
}

// HasConsumerId returns a boolean if a field has been set.
func (o *ConsumerNotification) HasConsumerId() bool {
	if o != nil && !IsNil(o.ConsumerId) {
		return true
	}

	return false
}

// SetConsumerId gets a reference to the given string and assigns it to the ConsumerId field.
func (o *ConsumerNotification) SetConsumerId(v string) {
	o.ConsumerId = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *ConsumerNotification) GetMsg() ConsumerNotificationMsg {
	if o == nil || IsNil(o.Msg) {
		var ret ConsumerNotificationMsg
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNotification) GetMsgOk() (*ConsumerNotificationMsg, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *ConsumerNotification) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given ConsumerNotificationMsg and assigns it to the Msg field.
func (o *ConsumerNotification) SetMsg(v ConsumerNotificationMsg) {
	o.Msg = &v
}

func (o ConsumerNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerId) {
		toSerialize["consumerId"] = o.ConsumerId
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	return toSerialize, nil
}

type NullableConsumerNotification struct {
	value *ConsumerNotification
	isSet bool
}

func (v NullableConsumerNotification) Get() *ConsumerNotification {
	return v.value
}

func (v *NullableConsumerNotification) Set(val *ConsumerNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerNotification(val *ConsumerNotification) *NullableConsumerNotification {
	return &NullableConsumerNotification{value: val, isSet: true}
}

func (v NullableConsumerNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


