/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// NexthopAddressInfo - The address info related to a nexthop. It could be an IP address or a service depending on the type.
type NexthopAddressInfo struct {
	NexthopIPInfo *NexthopIPInfo
	NexthopServiceInfo *NexthopServiceInfo
}

// NexthopIPInfoAsNexthopAddressInfo is a convenience function that returns NexthopIPInfo wrapped in NexthopAddressInfo
func NexthopIPInfoAsNexthopAddressInfo(v *NexthopIPInfo) NexthopAddressInfo {
	return NexthopAddressInfo{
		NexthopIPInfo: v,
	}
}

// NexthopServiceInfoAsNexthopAddressInfo is a convenience function that returns NexthopServiceInfo wrapped in NexthopAddressInfo
func NexthopServiceInfoAsNexthopAddressInfo(v *NexthopServiceInfo) NexthopAddressInfo {
	return NexthopAddressInfo{
		NexthopServiceInfo: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *NexthopAddressInfo) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into NexthopIPInfo
	err = newStrictDecoder(data).Decode(&dst.NexthopIPInfo)
	if err == nil {
		jsonNexthopIPInfo, _ := json.Marshal(dst.NexthopIPInfo)
		if string(jsonNexthopIPInfo) == "{}" { // empty struct
			dst.NexthopIPInfo = nil
		} else {
			if err = validator.Validate(dst.NexthopIPInfo); err != nil {
				dst.NexthopIPInfo = nil
			} else {
				match++
			}
		}
	} else {
		dst.NexthopIPInfo = nil
	}

	// try to unmarshal data into NexthopServiceInfo
	err = newStrictDecoder(data).Decode(&dst.NexthopServiceInfo)
	if err == nil {
		jsonNexthopServiceInfo, _ := json.Marshal(dst.NexthopServiceInfo)
		if string(jsonNexthopServiceInfo) == "{}" { // empty struct
			dst.NexthopServiceInfo = nil
		} else {
			if err = validator.Validate(dst.NexthopServiceInfo); err != nil {
				dst.NexthopServiceInfo = nil
			} else {
				match++
			}
		}
	} else {
		dst.NexthopServiceInfo = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.NexthopIPInfo = nil
		dst.NexthopServiceInfo = nil

		return fmt.Errorf("data matches more than one schema in oneOf(NexthopAddressInfo)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(NexthopAddressInfo)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NexthopAddressInfo) MarshalJSON() ([]byte, error) {
	if src.NexthopIPInfo != nil {
		return json.Marshal(&src.NexthopIPInfo)
	}

	if src.NexthopServiceInfo != nil {
		return json.Marshal(&src.NexthopServiceInfo)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NexthopAddressInfo) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.NexthopIPInfo != nil {
		return obj.NexthopIPInfo
	}

	if obj.NexthopServiceInfo != nil {
		return obj.NexthopServiceInfo
	}

	// all schemas are nil
	return nil
}

type NullableNexthopAddressInfo struct {
	value *NexthopAddressInfo
	isSet bool
}

func (v NullableNexthopAddressInfo) Get() *NexthopAddressInfo {
	return v.value
}

func (v *NullableNexthopAddressInfo) Set(val *NexthopAddressInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopAddressInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopAddressInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopAddressInfo(val *NexthopAddressInfo) *NullableNexthopAddressInfo {
	return &NullableNexthopAddressInfo{value: val, isSet: true}
}

func (v NullableNexthopAddressInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopAddressInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


