/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NexthopRegisterItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopRegisterItem{}

// NexthopRegisterItem The address info related to a query of a nexthop.
type NexthopRegisterItem struct {
	// A valid IP address.
	Address string `json:"address"`
	AddressFamily AddressFamily `json:"addressFamily"`
}

type _NexthopRegisterItem NexthopRegisterItem

// NewNexthopRegisterItem instantiates a new NexthopRegisterItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopRegisterItem(address string, addressFamily AddressFamily) *NexthopRegisterItem {
	this := NexthopRegisterItem{}
	this.Address = address
	this.AddressFamily = addressFamily
	return &this
}

// NewNexthopRegisterItemWithDefaults instantiates a new NexthopRegisterItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopRegisterItemWithDefaults() *NexthopRegisterItem {
	this := NexthopRegisterItem{}
	return &this
}

// GetAddress returns the Address field value
func (o *NexthopRegisterItem) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NexthopRegisterItem) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NexthopRegisterItem) SetAddress(v string) {
	o.Address = v
}

// GetAddressFamily returns the AddressFamily field value
func (o *NexthopRegisterItem) GetAddressFamily() AddressFamily {
	if o == nil {
		var ret AddressFamily
		return ret
	}

	return o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value
// and a boolean to check if the value has been set.
func (o *NexthopRegisterItem) GetAddressFamilyOk() (*AddressFamily, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddressFamily, true
}

// SetAddressFamily sets field value
func (o *NexthopRegisterItem) SetAddressFamily(v AddressFamily) {
	o.AddressFamily = v
}

func (o NexthopRegisterItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopRegisterItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["addressFamily"] = o.AddressFamily
	return toSerialize, nil
}

func (o *NexthopRegisterItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"addressFamily",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNexthopRegisterItem := _NexthopRegisterItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNexthopRegisterItem)

	if err != nil {
		return err
	}

	*o = NexthopRegisterItem(varNexthopRegisterItem)

	return err
}

type NullableNexthopRegisterItem struct {
	value *NexthopRegisterItem
	isSet bool
}

func (v NullableNexthopRegisterItem) Get() *NexthopRegisterItem {
	return v.value
}

func (v *NullableNexthopRegisterItem) Set(val *NexthopRegisterItem) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopRegisterItem) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopRegisterItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopRegisterItem(val *NexthopRegisterItem) *NullableNexthopRegisterItem {
	return &NullableNexthopRegisterItem{value: val, isSet: true}
}

func (v NullableNexthopRegisterItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopRegisterItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


