/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IpNexthop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpNexthop{}

// IpNexthop Nexthop IP address and family.
type IpNexthop struct {
	// A valid IP address.
	Address string `json:"address"`
	AddressFamily AddressFamily `json:"addressFamily"`
}

type _IpNexthop IpNexthop

// NewIpNexthop instantiates a new IpNexthop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpNexthop(address string, addressFamily AddressFamily) *IpNexthop {
	this := IpNexthop{}
	this.Address = address
	this.AddressFamily = addressFamily
	return &this
}

// NewIpNexthopWithDefaults instantiates a new IpNexthop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpNexthopWithDefaults() *IpNexthop {
	this := IpNexthop{}
	return &this
}

// GetAddress returns the Address field value
func (o *IpNexthop) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *IpNexthop) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *IpNexthop) SetAddress(v string) {
	o.Address = v
}

// GetAddressFamily returns the AddressFamily field value
func (o *IpNexthop) GetAddressFamily() AddressFamily {
	if o == nil {
		var ret AddressFamily
		return ret
	}

	return o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value
// and a boolean to check if the value has been set.
func (o *IpNexthop) GetAddressFamilyOk() (*AddressFamily, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddressFamily, true
}

// SetAddressFamily sets field value
func (o *IpNexthop) SetAddressFamily(v AddressFamily) {
	o.AddressFamily = v
}

func (o IpNexthop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpNexthop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["addressFamily"] = o.AddressFamily
	return toSerialize, nil
}

func (o *IpNexthop) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"addressFamily",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIpNexthop := _IpNexthop{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIpNexthop)

	if err != nil {
		return err
	}

	*o = IpNexthop(varIpNexthop)

	return err
}

type NullableIpNexthop struct {
	value *IpNexthop
	isSet bool
}

func (v NullableIpNexthop) Get() *IpNexthop {
	return v.value
}

func (v *NullableIpNexthop) Set(val *IpNexthop) {
	v.value = val
	v.isSet = true
}

func (v NullableIpNexthop) IsSet() bool {
	return v.isSet
}

func (v *NullableIpNexthop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpNexthop(val *IpNexthop) *NullableIpNexthop {
	return &NullableIpNexthop{value: val, isSet: true}
}

func (v NullableIpNexthop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpNexthop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


