/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NexthopServiceInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NexthopServiceInfo{}

// NexthopServiceInfo struct for NexthopServiceInfo
type NexthopServiceInfo struct {
	// Name of the service.
	ServiceName string `json:"serviceName"`
	// Pod unique ID.
	InstanceId *string `json:"instanceId,omitempty"`
	Type string `json:"type"`
}

type _NexthopServiceInfo NexthopServiceInfo

// NewNexthopServiceInfo instantiates a new NexthopServiceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNexthopServiceInfo(serviceName string, type_ string) *NexthopServiceInfo {
	this := NexthopServiceInfo{}
	this.ServiceName = serviceName
	this.Type = type_
	return &this
}

// NewNexthopServiceInfoWithDefaults instantiates a new NexthopServiceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNexthopServiceInfoWithDefaults() *NexthopServiceInfo {
	this := NexthopServiceInfo{}
	return &this
}

// GetServiceName returns the ServiceName field value
func (o *NexthopServiceInfo) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *NexthopServiceInfo) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *NexthopServiceInfo) SetServiceName(v string) {
	o.ServiceName = v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *NexthopServiceInfo) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NexthopServiceInfo) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *NexthopServiceInfo) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *NexthopServiceInfo) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetType returns the Type field value
func (o *NexthopServiceInfo) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NexthopServiceInfo) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NexthopServiceInfo) SetType(v string) {
	o.Type = v
}

func (o NexthopServiceInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NexthopServiceInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serviceName"] = o.ServiceName
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *NexthopServiceInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceName",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNexthopServiceInfo := _NexthopServiceInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNexthopServiceInfo)

	if err != nil {
		return err
	}

	*o = NexthopServiceInfo(varNexthopServiceInfo)

	return err
}

type NullableNexthopServiceInfo struct {
	value *NexthopServiceInfo
	isSet bool
}

func (v NullableNexthopServiceInfo) Get() *NexthopServiceInfo {
	return v.value
}

func (v *NullableNexthopServiceInfo) Set(val *NexthopServiceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableNexthopServiceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableNexthopServiceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNexthopServiceInfo(val *NexthopServiceInfo) *NullableNexthopServiceInfo {
	return &NullableNexthopServiceInfo{value: val, isSet: true}
}

func (v NullableNexthopServiceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNexthopServiceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


