/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsumerNexthopsNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerNexthopsNotification{}

// ConsumerNexthopsNotification struct for ConsumerNexthopsNotification
type ConsumerNexthopsNotification struct {
	Type *string `json:"type,omitempty"`
	Nexthops []ConsumerNexthopsNotificationItem `json:"nexthops,omitempty"`
}

// NewConsumerNexthopsNotification instantiates a new ConsumerNexthopsNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerNexthopsNotification() *ConsumerNexthopsNotification {
	this := ConsumerNexthopsNotification{}
	return &this
}

// NewConsumerNexthopsNotificationWithDefaults instantiates a new ConsumerNexthopsNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerNexthopsNotificationWithDefaults() *ConsumerNexthopsNotification {
	this := ConsumerNexthopsNotification{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotification) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotification) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotification) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ConsumerNexthopsNotification) SetType(v string) {
	o.Type = &v
}

// GetNexthops returns the Nexthops field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotification) GetNexthops() []ConsumerNexthopsNotificationItem {
	if o == nil || IsNil(o.Nexthops) {
		var ret []ConsumerNexthopsNotificationItem
		return ret
	}
	return o.Nexthops
}

// GetNexthopsOk returns a tuple with the Nexthops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotification) GetNexthopsOk() ([]ConsumerNexthopsNotificationItem, bool) {
	if o == nil || IsNil(o.Nexthops) {
		return nil, false
	}
	return o.Nexthops, true
}

// HasNexthops returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotification) HasNexthops() bool {
	if o != nil && !IsNil(o.Nexthops) {
		return true
	}

	return false
}

// SetNexthops gets a reference to the given []ConsumerNexthopsNotificationItem and assigns it to the Nexthops field.
func (o *ConsumerNexthopsNotification) SetNexthops(v []ConsumerNexthopsNotificationItem) {
	o.Nexthops = v
}

func (o ConsumerNexthopsNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerNexthopsNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Nexthops) {
		toSerialize["nexthops"] = o.Nexthops
	}
	return toSerialize, nil
}

type NullableConsumerNexthopsNotification struct {
	value *ConsumerNexthopsNotification
	isSet bool
}

func (v NullableConsumerNexthopsNotification) Get() *ConsumerNexthopsNotification {
	return v.value
}

func (v *NullableConsumerNexthopsNotification) Set(val *ConsumerNexthopsNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerNexthopsNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerNexthopsNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerNexthopsNotification(val *ConsumerNexthopsNotification) *NullableConsumerNexthopsNotification {
	return &NullableConsumerNexthopsNotification{value: val, isSet: true}
}

func (v NullableConsumerNexthopsNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerNexthopsNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


