/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsumerRoutesNotificationItemNexthop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerRoutesNotificationItemNexthop{}

// ConsumerRoutesNotificationItemNexthop Nexthop identifer which composed by nexthop networkInstance and nexthop id. If above \"action\" is \"add\", the item is required.
type ConsumerRoutesNotificationItemNexthop struct {
	// The network instance which nexthop belongs to.
	NetworkInstance *string `json:"networkInstance,omitempty"`
	// Nexthop id, identify a nexthop.
	Id *int32 `json:"id,omitempty"`
}

// NewConsumerRoutesNotificationItemNexthop instantiates a new ConsumerRoutesNotificationItemNexthop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerRoutesNotificationItemNexthop() *ConsumerRoutesNotificationItemNexthop {
	this := ConsumerRoutesNotificationItemNexthop{}
	return &this
}

// NewConsumerRoutesNotificationItemNexthopWithDefaults instantiates a new ConsumerRoutesNotificationItemNexthop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerRoutesNotificationItemNexthopWithDefaults() *ConsumerRoutesNotificationItemNexthop {
	this := ConsumerRoutesNotificationItemNexthop{}
	return &this
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *ConsumerRoutesNotificationItemNexthop) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerRoutesNotificationItemNexthop) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *ConsumerRoutesNotificationItemNexthop) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *ConsumerRoutesNotificationItemNexthop) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ConsumerRoutesNotificationItemNexthop) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerRoutesNotificationItemNexthop) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ConsumerRoutesNotificationItemNexthop) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ConsumerRoutesNotificationItemNexthop) SetId(v int32) {
	o.Id = &v
}

func (o ConsumerRoutesNotificationItemNexthop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerRoutesNotificationItemNexthop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkInstance) {
		toSerialize["networkInstance"] = o.NetworkInstance
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableConsumerRoutesNotificationItemNexthop struct {
	value *ConsumerRoutesNotificationItemNexthop
	isSet bool
}

func (v NullableConsumerRoutesNotificationItemNexthop) Get() *ConsumerRoutesNotificationItemNexthop {
	return v.value
}

func (v *NullableConsumerRoutesNotificationItemNexthop) Set(val *ConsumerRoutesNotificationItemNexthop) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerRoutesNotificationItemNexthop) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerRoutesNotificationItemNexthop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerRoutesNotificationItemNexthop(val *ConsumerRoutesNotificationItemNexthop) *NullableConsumerRoutesNotificationItemNexthop {
	return &NullableConsumerRoutesNotificationItemNexthop{value: val, isSet: true}
}

func (v NullableConsumerRoutesNotificationItemNexthop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerRoutesNotificationItemNexthop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


