/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsumerUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerUpdate{}

// ConsumerUpdate used for consumer client to update its information. routeFilters and networkInstanceFilters are used to specify routes/nexthops that they need be download to consumer. Only routes/nexthops that meet both routeFilters and networkInstanceFilters conditions will be downloaded to consumer.
type ConsumerUpdate struct {
	// Currently not implemented. For consumer client, used to filter routes as per route type when RIB publish routes to consumer. It shall include all route types that consumer need. Only routes/nexthops that meet both routeFilters and networkInstanceFilters conditions will be downloaded to consumer.
	RouteFilters []RouteType `json:"routeFilters"`
	// for consumer client, used to filter routes as per networkInstance when RIB publish routes to consumer. It shall include all MWs that consumer need. Only routes/nexthops that meet both routeFilters and networkInstanceFilters conditions will be downloaded to consumer.
	NetworkInstanceFilters []string `json:"networkInstanceFilters"`
}

type _ConsumerUpdate ConsumerUpdate

// NewConsumerUpdate instantiates a new ConsumerUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerUpdate(routeFilters []RouteType, networkInstanceFilters []string) *ConsumerUpdate {
	this := ConsumerUpdate{}
	this.RouteFilters = routeFilters
	this.NetworkInstanceFilters = networkInstanceFilters
	return &this
}

// NewConsumerUpdateWithDefaults instantiates a new ConsumerUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerUpdateWithDefaults() *ConsumerUpdate {
	this := ConsumerUpdate{}
	return &this
}

// GetRouteFilters returns the RouteFilters field value
func (o *ConsumerUpdate) GetRouteFilters() []RouteType {
	if o == nil {
		var ret []RouteType
		return ret
	}

	return o.RouteFilters
}

// GetRouteFiltersOk returns a tuple with the RouteFilters field value
// and a boolean to check if the value has been set.
func (o *ConsumerUpdate) GetRouteFiltersOk() ([]RouteType, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteFilters, true
}

// SetRouteFilters sets field value
func (o *ConsumerUpdate) SetRouteFilters(v []RouteType) {
	o.RouteFilters = v
}

// GetNetworkInstanceFilters returns the NetworkInstanceFilters field value
func (o *ConsumerUpdate) GetNetworkInstanceFilters() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.NetworkInstanceFilters
}

// GetNetworkInstanceFiltersOk returns a tuple with the NetworkInstanceFilters field value
// and a boolean to check if the value has been set.
func (o *ConsumerUpdate) GetNetworkInstanceFiltersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkInstanceFilters, true
}

// SetNetworkInstanceFilters sets field value
func (o *ConsumerUpdate) SetNetworkInstanceFilters(v []string) {
	o.NetworkInstanceFilters = v
}

func (o ConsumerUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["routeFilters"] = o.RouteFilters
	toSerialize["networkInstanceFilters"] = o.NetworkInstanceFilters
	return toSerialize, nil
}

func (o *ConsumerUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"routeFilters",
		"networkInstanceFilters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsumerUpdate := _ConsumerUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsumerUpdate)

	if err != nil {
		return err
	}

	*o = ConsumerUpdate(varConsumerUpdate)

	return err
}

type NullableConsumerUpdate struct {
	value *ConsumerUpdate
	isSet bool
}

func (v NullableConsumerUpdate) Get() *ConsumerUpdate {
	return v.value
}

func (v *NullableConsumerUpdate) Set(val *ConsumerUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerUpdate(val *ConsumerUpdate) *NullableConsumerUpdate {
	return &NullableConsumerUpdate{value: val, isSet: true}
}

func (v NullableConsumerUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


