/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsumerRoutesNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerRoutesNotification{}

// ConsumerRoutesNotification struct for ConsumerRoutesNotification
type ConsumerRoutesNotification struct {
	Type *string `json:"type,omitempty"`
	Routes []ConsumerRoutesNotificationItem `json:"routes,omitempty"`
}

// NewConsumerRoutesNotification instantiates a new ConsumerRoutesNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerRoutesNotification() *ConsumerRoutesNotification {
	this := ConsumerRoutesNotification{}
	return &this
}

// NewConsumerRoutesNotificationWithDefaults instantiates a new ConsumerRoutesNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerRoutesNotificationWithDefaults() *ConsumerRoutesNotification {
	this := ConsumerRoutesNotification{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ConsumerRoutesNotification) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerRoutesNotification) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ConsumerRoutesNotification) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ConsumerRoutesNotification) SetType(v string) {
	o.Type = &v
}

// GetRoutes returns the Routes field value if set, zero value otherwise.
func (o *ConsumerRoutesNotification) GetRoutes() []ConsumerRoutesNotificationItem {
	if o == nil || IsNil(o.Routes) {
		var ret []ConsumerRoutesNotificationItem
		return ret
	}
	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerRoutesNotification) GetRoutesOk() ([]ConsumerRoutesNotificationItem, bool) {
	if o == nil || IsNil(o.Routes) {
		return nil, false
	}
	return o.Routes, true
}

// HasRoutes returns a boolean if a field has been set.
func (o *ConsumerRoutesNotification) HasRoutes() bool {
	if o != nil && !IsNil(o.Routes) {
		return true
	}

	return false
}

// SetRoutes gets a reference to the given []ConsumerRoutesNotificationItem and assigns it to the Routes field.
func (o *ConsumerRoutesNotification) SetRoutes(v []ConsumerRoutesNotificationItem) {
	o.Routes = v
}

func (o ConsumerRoutesNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerRoutesNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Routes) {
		toSerialize["routes"] = o.Routes
	}
	return toSerialize, nil
}

type NullableConsumerRoutesNotification struct {
	value *ConsumerRoutesNotification
	isSet bool
}

func (v NullableConsumerRoutesNotification) Get() *ConsumerRoutesNotification {
	return v.value
}

func (v *NullableConsumerRoutesNotification) Set(val *ConsumerRoutesNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerRoutesNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerRoutesNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerRoutesNotification(val *ConsumerRoutesNotification) *NullableConsumerRoutesNotification {
	return &NullableConsumerRoutesNotification{value: val, isSet: true}
}

func (v NullableConsumerRoutesNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerRoutesNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


