/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// RouteNexthopInfoAttrInner - struct for RouteNexthopInfoAttrInner
type RouteNexthopInfoAttrInner struct {
	String *string
}

// stringAsRouteNexthopInfoAttrInner is a convenience function that returns string wrapped in RouteNexthopInfoAttrInner
func StringAsRouteNexthopInfoAttrInner(v *string) RouteNexthopInfoAttrInner {
	return RouteNexthopInfoAttrInner{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RouteNexthopInfoAttrInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RouteNexthopInfoAttrInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RouteNexthopInfoAttrInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RouteNexthopInfoAttrInner) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RouteNexthopInfoAttrInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRouteNexthopInfoAttrInner struct {
	value *RouteNexthopInfoAttrInner
	isSet bool
}

func (v NullableRouteNexthopInfoAttrInner) Get() *RouteNexthopInfoAttrInner {
	return v.value
}

func (v *NullableRouteNexthopInfoAttrInner) Set(val *RouteNexthopInfoAttrInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteNexthopInfoAttrInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteNexthopInfoAttrInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteNexthopInfoAttrInner(val *RouteNexthopInfoAttrInner) *NullableRouteNexthopInfoAttrInner {
	return &NullableRouteNexthopInfoAttrInner{value: val, isSet: true}
}

func (v NullableRouteNexthopInfoAttrInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteNexthopInfoAttrInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


