/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Consumer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Consumer{}

// Consumer struct for Consumer
type Consumer struct {
	// Indicates client name, for either Producer or Consumer. For route-engine, client name is like {cre-pod-name} + {static/bgp/ifm}, for data-plane, client name is like {dp-pod-name}, for client that is service, client name is like {service-name}.
	Id *string `json:"id,omitempty"`
	// Unit is second. Indicates how long RIB has not received the client\"s heartbeat before it considers the client to be dead. If not present, RIB will give a default value.
	KeepaliveTimeout *int32 `json:"keepaliveTimeout,omitempty"`
	// Currently not implemented. Cor consumer client, used to filter routes as per route type when RIB publish routes to consumer. Only routes/nexthops that meet both routeFilters and networkInstanceFilters conditions will be downloaded to consumer.
	RouteFilters []RouteType `json:"routeFilters"`
	// for consumer client, used to filter routes as per networkInstance when RIB publish routes to consumer. Only routes/nexthops that meet both routeFilters and networkInstanceFilters conditions will be downloaded to consumer.
	NetworkInstanceFilters []string `json:"networkInstanceFilters,omitempty"`
	// The location will be called to notify EOF information to consumer client. The location will be called to publish routes to consumer client.
	UrlCallback string `json:"urlCallback"`
}

type _Consumer Consumer

// NewConsumer instantiates a new Consumer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumer(routeFilters []RouteType, urlCallback string) *Consumer {
	this := Consumer{}
	this.RouteFilters = routeFilters
	this.UrlCallback = urlCallback
	return &this
}

// NewConsumerWithDefaults instantiates a new Consumer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerWithDefaults() *Consumer {
	this := Consumer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Consumer) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Consumer) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Consumer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Consumer) SetId(v string) {
	o.Id = &v
}

// GetKeepaliveTimeout returns the KeepaliveTimeout field value if set, zero value otherwise.
func (o *Consumer) GetKeepaliveTimeout() int32 {
	if o == nil || IsNil(o.KeepaliveTimeout) {
		var ret int32
		return ret
	}
	return *o.KeepaliveTimeout
}

// GetKeepaliveTimeoutOk returns a tuple with the KeepaliveTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Consumer) GetKeepaliveTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.KeepaliveTimeout) {
		return nil, false
	}
	return o.KeepaliveTimeout, true
}

// HasKeepaliveTimeout returns a boolean if a field has been set.
func (o *Consumer) HasKeepaliveTimeout() bool {
	if o != nil && !IsNil(o.KeepaliveTimeout) {
		return true
	}

	return false
}

// SetKeepaliveTimeout gets a reference to the given int32 and assigns it to the KeepaliveTimeout field.
func (o *Consumer) SetKeepaliveTimeout(v int32) {
	o.KeepaliveTimeout = &v
}

// GetRouteFilters returns the RouteFilters field value
func (o *Consumer) GetRouteFilters() []RouteType {
	if o == nil {
		var ret []RouteType
		return ret
	}

	return o.RouteFilters
}

// GetRouteFiltersOk returns a tuple with the RouteFilters field value
// and a boolean to check if the value has been set.
func (o *Consumer) GetRouteFiltersOk() ([]RouteType, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteFilters, true
}

// SetRouteFilters sets field value
func (o *Consumer) SetRouteFilters(v []RouteType) {
	o.RouteFilters = v
}

// GetNetworkInstanceFilters returns the NetworkInstanceFilters field value if set, zero value otherwise.
func (o *Consumer) GetNetworkInstanceFilters() []string {
	if o == nil || IsNil(o.NetworkInstanceFilters) {
		var ret []string
		return ret
	}
	return o.NetworkInstanceFilters
}

// GetNetworkInstanceFiltersOk returns a tuple with the NetworkInstanceFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Consumer) GetNetworkInstanceFiltersOk() ([]string, bool) {
	if o == nil || IsNil(o.NetworkInstanceFilters) {
		return nil, false
	}
	return o.NetworkInstanceFilters, true
}

// HasNetworkInstanceFilters returns a boolean if a field has been set.
func (o *Consumer) HasNetworkInstanceFilters() bool {
	if o != nil && !IsNil(o.NetworkInstanceFilters) {
		return true
	}

	return false
}

// SetNetworkInstanceFilters gets a reference to the given []string and assigns it to the NetworkInstanceFilters field.
func (o *Consumer) SetNetworkInstanceFilters(v []string) {
	o.NetworkInstanceFilters = v
}

// GetUrlCallback returns the UrlCallback field value
func (o *Consumer) GetUrlCallback() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlCallback
}

// GetUrlCallbackOk returns a tuple with the UrlCallback field value
// and a boolean to check if the value has been set.
func (o *Consumer) GetUrlCallbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlCallback, true
}

// SetUrlCallback sets field value
func (o *Consumer) SetUrlCallback(v string) {
	o.UrlCallback = v
}

func (o Consumer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Consumer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.KeepaliveTimeout) {
		toSerialize["keepaliveTimeout"] = o.KeepaliveTimeout
	}
	toSerialize["routeFilters"] = o.RouteFilters
	if !IsNil(o.NetworkInstanceFilters) {
		toSerialize["networkInstanceFilters"] = o.NetworkInstanceFilters
	}
	toSerialize["urlCallback"] = o.UrlCallback
	return toSerialize, nil
}

func (o *Consumer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"routeFilters",
		"urlCallback",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsumer := _Consumer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsumer)

	if err != nil {
		return err
	}

	*o = Consumer(varConsumer)

	return err
}

type NullableConsumer struct {
	value *Consumer
	isSet bool
}

func (v NullableConsumer) Get() *Consumer {
	return v.value
}

func (v *NullableConsumer) Set(val *Consumer) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumer) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumer(val *Consumer) *NullableConsumer {
	return &NullableConsumer{value: val, isSet: true}
}

func (v NullableConsumer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


