/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the QueryNexthopNotificationItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryNexthopNotificationItem{}

// QueryNexthopNotificationItem Query nexthop notification item.
type QueryNexthopNotificationItem struct {
	// A valid IP address.
	Address string `json:"address"`
	AddressFamily AddressFamily `json:"addressFamily"`
	NetworkInstance *string `json:"networkInstance,omitempty"`
	ProtocolType *RouteType `json:"protocolType,omitempty"`
	Flags []QueryNexthopNotificationItemAllOfFlags `json:"flags,omitempty"`
	// The address of the route nexthop to the queried address
	ViaAddressInfo *NexthopAddressInfo `json:"viaAddressInfo,omitempty"`
	Metric *int32 `json:"metric,omitempty"`
	ViaNetworkInstance *string `json:"viaNetworkInstance,omitempty"`
	NexthopTimestamp *time.Time `json:"nexthopTimestamp,omitempty"`
	// Nexthop priority. The higher the value, the lower the priority
	Priority *int32 `json:"priority,omitempty"`
}

type _QueryNexthopNotificationItem QueryNexthopNotificationItem

// NewQueryNexthopNotificationItem instantiates a new QueryNexthopNotificationItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryNexthopNotificationItem(address string, addressFamily AddressFamily) *QueryNexthopNotificationItem {
	this := QueryNexthopNotificationItem{}
	this.Address = address
	this.AddressFamily = addressFamily
	return &this
}

// NewQueryNexthopNotificationItemWithDefaults instantiates a new QueryNexthopNotificationItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryNexthopNotificationItemWithDefaults() *QueryNexthopNotificationItem {
	this := QueryNexthopNotificationItem{}
	return &this
}

// GetAddress returns the Address field value
func (o *QueryNexthopNotificationItem) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *QueryNexthopNotificationItem) SetAddress(v string) {
	o.Address = v
}

// GetAddressFamily returns the AddressFamily field value
func (o *QueryNexthopNotificationItem) GetAddressFamily() AddressFamily {
	if o == nil {
		var ret AddressFamily
		return ret
	}

	return o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetAddressFamilyOk() (*AddressFamily, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddressFamily, true
}

// SetAddressFamily sets field value
func (o *QueryNexthopNotificationItem) SetAddressFamily(v AddressFamily) {
	o.AddressFamily = v
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *QueryNexthopNotificationItem) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetProtocolType returns the ProtocolType field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetProtocolType() RouteType {
	if o == nil || IsNil(o.ProtocolType) {
		var ret RouteType
		return ret
	}
	return *o.ProtocolType
}

// GetProtocolTypeOk returns a tuple with the ProtocolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetProtocolTypeOk() (*RouteType, bool) {
	if o == nil || IsNil(o.ProtocolType) {
		return nil, false
	}
	return o.ProtocolType, true
}

// HasProtocolType returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasProtocolType() bool {
	if o != nil && !IsNil(o.ProtocolType) {
		return true
	}

	return false
}

// SetProtocolType gets a reference to the given RouteType and assigns it to the ProtocolType field.
func (o *QueryNexthopNotificationItem) SetProtocolType(v RouteType) {
	o.ProtocolType = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetFlags() []QueryNexthopNotificationItemAllOfFlags {
	if o == nil || IsNil(o.Flags) {
		var ret []QueryNexthopNotificationItemAllOfFlags
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetFlagsOk() ([]QueryNexthopNotificationItemAllOfFlags, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []QueryNexthopNotificationItemAllOfFlags and assigns it to the Flags field.
func (o *QueryNexthopNotificationItem) SetFlags(v []QueryNexthopNotificationItemAllOfFlags) {
	o.Flags = v
}

// GetViaAddressInfo returns the ViaAddressInfo field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetViaAddressInfo() NexthopAddressInfo {
	if o == nil || IsNil(o.ViaAddressInfo) {
		var ret NexthopAddressInfo
		return ret
	}
	return *o.ViaAddressInfo
}

// GetViaAddressInfoOk returns a tuple with the ViaAddressInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetViaAddressInfoOk() (*NexthopAddressInfo, bool) {
	if o == nil || IsNil(o.ViaAddressInfo) {
		return nil, false
	}
	return o.ViaAddressInfo, true
}

// HasViaAddressInfo returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasViaAddressInfo() bool {
	if o != nil && !IsNil(o.ViaAddressInfo) {
		return true
	}

	return false
}

// SetViaAddressInfo gets a reference to the given NexthopAddressInfo and assigns it to the ViaAddressInfo field.
func (o *QueryNexthopNotificationItem) SetViaAddressInfo(v NexthopAddressInfo) {
	o.ViaAddressInfo = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetMetric() int32 {
	if o == nil || IsNil(o.Metric) {
		var ret int32
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetMetricOk() (*int32, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given int32 and assigns it to the Metric field.
func (o *QueryNexthopNotificationItem) SetMetric(v int32) {
	o.Metric = &v
}

// GetViaNetworkInstance returns the ViaNetworkInstance field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetViaNetworkInstance() string {
	if o == nil || IsNil(o.ViaNetworkInstance) {
		var ret string
		return ret
	}
	return *o.ViaNetworkInstance
}

// GetViaNetworkInstanceOk returns a tuple with the ViaNetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetViaNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.ViaNetworkInstance) {
		return nil, false
	}
	return o.ViaNetworkInstance, true
}

// HasViaNetworkInstance returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasViaNetworkInstance() bool {
	if o != nil && !IsNil(o.ViaNetworkInstance) {
		return true
	}

	return false
}

// SetViaNetworkInstance gets a reference to the given string and assigns it to the ViaNetworkInstance field.
func (o *QueryNexthopNotificationItem) SetViaNetworkInstance(v string) {
	o.ViaNetworkInstance = &v
}

// GetNexthopTimestamp returns the NexthopTimestamp field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetNexthopTimestamp() time.Time {
	if o == nil || IsNil(o.NexthopTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.NexthopTimestamp
}

// GetNexthopTimestampOk returns a tuple with the NexthopTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetNexthopTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NexthopTimestamp) {
		return nil, false
	}
	return o.NexthopTimestamp, true
}

// HasNexthopTimestamp returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasNexthopTimestamp() bool {
	if o != nil && !IsNil(o.NexthopTimestamp) {
		return true
	}

	return false
}

// SetNexthopTimestamp gets a reference to the given time.Time and assigns it to the NexthopTimestamp field.
func (o *QueryNexthopNotificationItem) SetNexthopTimestamp(v time.Time) {
	o.NexthopTimestamp = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *QueryNexthopNotificationItem) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryNexthopNotificationItem) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *QueryNexthopNotificationItem) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *QueryNexthopNotificationItem) SetPriority(v int32) {
	o.Priority = &v
}

func (o QueryNexthopNotificationItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryNexthopNotificationItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["addressFamily"] = o.AddressFamily
	if !IsNil(o.NetworkInstance) {
		toSerialize["networkInstance"] = o.NetworkInstance
	}
	if !IsNil(o.ProtocolType) {
		toSerialize["protocolType"] = o.ProtocolType
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.ViaAddressInfo) {
		toSerialize["viaAddressInfo"] = o.ViaAddressInfo
	}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.ViaNetworkInstance) {
		toSerialize["viaNetworkInstance"] = o.ViaNetworkInstance
	}
	if !IsNil(o.NexthopTimestamp) {
		toSerialize["nexthopTimestamp"] = o.NexthopTimestamp
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

func (o *QueryNexthopNotificationItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"addressFamily",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryNexthopNotificationItem := _QueryNexthopNotificationItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryNexthopNotificationItem)

	if err != nil {
		return err
	}

	*o = QueryNexthopNotificationItem(varQueryNexthopNotificationItem)

	return err
}

type NullableQueryNexthopNotificationItem struct {
	value *QueryNexthopNotificationItem
	isSet bool
}

func (v NullableQueryNexthopNotificationItem) Get() *QueryNexthopNotificationItem {
	return v.value
}

func (v *NullableQueryNexthopNotificationItem) Set(val *QueryNexthopNotificationItem) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryNexthopNotificationItem) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryNexthopNotificationItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryNexthopNotificationItem(val *QueryNexthopNotificationItem) *NullableQueryNexthopNotificationItem {
	return &NullableQueryNexthopNotificationItem{value: val, isSet: true}
}

func (v NullableQueryNexthopNotificationItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryNexthopNotificationItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


