/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// QueryNexthopNotificationItemAllOfFlags - struct for QueryNexthopNotificationItemAllOfFlags
type QueryNexthopNotificationItemAllOfFlags struct {
	String *string
}

// stringAsQueryNexthopNotificationItemAllOfFlags is a convenience function that returns string wrapped in QueryNexthopNotificationItemAllOfFlags
func StringAsQueryNexthopNotificationItemAllOfFlags(v *string) QueryNexthopNotificationItemAllOfFlags {
	return QueryNexthopNotificationItemAllOfFlags{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *QueryNexthopNotificationItemAllOfFlags) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(QueryNexthopNotificationItemAllOfFlags)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(QueryNexthopNotificationItemAllOfFlags)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src QueryNexthopNotificationItemAllOfFlags) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *QueryNexthopNotificationItemAllOfFlags) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableQueryNexthopNotificationItemAllOfFlags struct {
	value *QueryNexthopNotificationItemAllOfFlags
	isSet bool
}

func (v NullableQueryNexthopNotificationItemAllOfFlags) Get() *QueryNexthopNotificationItemAllOfFlags {
	return v.value
}

func (v *NullableQueryNexthopNotificationItemAllOfFlags) Set(val *QueryNexthopNotificationItemAllOfFlags) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryNexthopNotificationItemAllOfFlags) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryNexthopNotificationItemAllOfFlags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryNexthopNotificationItemAllOfFlags(val *QueryNexthopNotificationItemAllOfFlags) *NullableQueryNexthopNotificationItemAllOfFlags {
	return &NullableQueryNexthopNotificationItemAllOfFlags{value: val, isSet: true}
}

func (v NullableQueryNexthopNotificationItemAllOfFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryNexthopNotificationItemAllOfFlags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


