/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QueryPrefixNotificationItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryPrefixNotificationItem{}

// QueryPrefixNotificationItem struct for QueryPrefixNotificationItem
type QueryPrefixNotificationItem struct {
	IsFound *QueryPrefixNotificationItemIsFound `json:"isFound,omitempty"`
	NetworkInstance *string `json:"networkInstance,omitempty"`
	AddressFamily *AddressFamily `json:"addressFamily,omitempty"`
	// A valid IP prefix.
	Prefix *string `json:"prefix,omitempty"`
	RetNexthopType *PrefixNexthopType `json:"retNexthopType,omitempty"`
	NumServiceNexthop *int32 `json:"numServiceNexthop,omitempty"`
	// number of ip type\"s nexthop
	NumIpNexthop *int32 `json:"numIpNexthop,omitempty"`
	// number of lsp type\"s nexthop
	NumLspNexthop *int32 `json:"numLspNexthop,omitempty"`
	// if across networkInstance
	InterNetworkInstanceFlag *bool `json:"interNetworkInstanceFlag,omitempty"`
	// A valid IP prefix.
	MatchedPrefix *string `json:"matchedPrefix,omitempty"`
	// nexthops of matching prefixes found
	Nexthops []QueryPrefixNotificationNexthopItem `json:"nexthops,omitempty"`
}

// NewQueryPrefixNotificationItem instantiates a new QueryPrefixNotificationItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryPrefixNotificationItem() *QueryPrefixNotificationItem {
	this := QueryPrefixNotificationItem{}
	return &this
}

// NewQueryPrefixNotificationItemWithDefaults instantiates a new QueryPrefixNotificationItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryPrefixNotificationItemWithDefaults() *QueryPrefixNotificationItem {
	this := QueryPrefixNotificationItem{}
	return &this
}

// GetIsFound returns the IsFound field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetIsFound() QueryPrefixNotificationItemIsFound {
	if o == nil || IsNil(o.IsFound) {
		var ret QueryPrefixNotificationItemIsFound
		return ret
	}
	return *o.IsFound
}

// GetIsFoundOk returns a tuple with the IsFound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetIsFoundOk() (*QueryPrefixNotificationItemIsFound, bool) {
	if o == nil || IsNil(o.IsFound) {
		return nil, false
	}
	return o.IsFound, true
}

// HasIsFound returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasIsFound() bool {
	if o != nil && !IsNil(o.IsFound) {
		return true
	}

	return false
}

// SetIsFound gets a reference to the given QueryPrefixNotificationItemIsFound and assigns it to the IsFound field.
func (o *QueryPrefixNotificationItem) SetIsFound(v QueryPrefixNotificationItemIsFound) {
	o.IsFound = &v
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *QueryPrefixNotificationItem) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetAddressFamily() AddressFamily {
	if o == nil || IsNil(o.AddressFamily) {
		var ret AddressFamily
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetAddressFamilyOk() (*AddressFamily, bool) {
	if o == nil || IsNil(o.AddressFamily) {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasAddressFamily() bool {
	if o != nil && !IsNil(o.AddressFamily) {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given AddressFamily and assigns it to the AddressFamily field.
func (o *QueryPrefixNotificationItem) SetAddressFamily(v AddressFamily) {
	o.AddressFamily = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *QueryPrefixNotificationItem) SetPrefix(v string) {
	o.Prefix = &v
}

// GetRetNexthopType returns the RetNexthopType field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetRetNexthopType() PrefixNexthopType {
	if o == nil || IsNil(o.RetNexthopType) {
		var ret PrefixNexthopType
		return ret
	}
	return *o.RetNexthopType
}

// GetRetNexthopTypeOk returns a tuple with the RetNexthopType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetRetNexthopTypeOk() (*PrefixNexthopType, bool) {
	if o == nil || IsNil(o.RetNexthopType) {
		return nil, false
	}
	return o.RetNexthopType, true
}

// HasRetNexthopType returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasRetNexthopType() bool {
	if o != nil && !IsNil(o.RetNexthopType) {
		return true
	}

	return false
}

// SetRetNexthopType gets a reference to the given PrefixNexthopType and assigns it to the RetNexthopType field.
func (o *QueryPrefixNotificationItem) SetRetNexthopType(v PrefixNexthopType) {
	o.RetNexthopType = &v
}

// GetNumServiceNexthop returns the NumServiceNexthop field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetNumServiceNexthop() int32 {
	if o == nil || IsNil(o.NumServiceNexthop) {
		var ret int32
		return ret
	}
	return *o.NumServiceNexthop
}

// GetNumServiceNexthopOk returns a tuple with the NumServiceNexthop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetNumServiceNexthopOk() (*int32, bool) {
	if o == nil || IsNil(o.NumServiceNexthop) {
		return nil, false
	}
	return o.NumServiceNexthop, true
}

// HasNumServiceNexthop returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasNumServiceNexthop() bool {
	if o != nil && !IsNil(o.NumServiceNexthop) {
		return true
	}

	return false
}

// SetNumServiceNexthop gets a reference to the given int32 and assigns it to the NumServiceNexthop field.
func (o *QueryPrefixNotificationItem) SetNumServiceNexthop(v int32) {
	o.NumServiceNexthop = &v
}

// GetNumIpNexthop returns the NumIpNexthop field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetNumIpNexthop() int32 {
	if o == nil || IsNil(o.NumIpNexthop) {
		var ret int32
		return ret
	}
	return *o.NumIpNexthop
}

// GetNumIpNexthopOk returns a tuple with the NumIpNexthop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetNumIpNexthopOk() (*int32, bool) {
	if o == nil || IsNil(o.NumIpNexthop) {
		return nil, false
	}
	return o.NumIpNexthop, true
}

// HasNumIpNexthop returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasNumIpNexthop() bool {
	if o != nil && !IsNil(o.NumIpNexthop) {
		return true
	}

	return false
}

// SetNumIpNexthop gets a reference to the given int32 and assigns it to the NumIpNexthop field.
func (o *QueryPrefixNotificationItem) SetNumIpNexthop(v int32) {
	o.NumIpNexthop = &v
}

// GetNumLspNexthop returns the NumLspNexthop field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetNumLspNexthop() int32 {
	if o == nil || IsNil(o.NumLspNexthop) {
		var ret int32
		return ret
	}
	return *o.NumLspNexthop
}

// GetNumLspNexthopOk returns a tuple with the NumLspNexthop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetNumLspNexthopOk() (*int32, bool) {
	if o == nil || IsNil(o.NumLspNexthop) {
		return nil, false
	}
	return o.NumLspNexthop, true
}

// HasNumLspNexthop returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasNumLspNexthop() bool {
	if o != nil && !IsNil(o.NumLspNexthop) {
		return true
	}

	return false
}

// SetNumLspNexthop gets a reference to the given int32 and assigns it to the NumLspNexthop field.
func (o *QueryPrefixNotificationItem) SetNumLspNexthop(v int32) {
	o.NumLspNexthop = &v
}

// GetInterNetworkInstanceFlag returns the InterNetworkInstanceFlag field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetInterNetworkInstanceFlag() bool {
	if o == nil || IsNil(o.InterNetworkInstanceFlag) {
		var ret bool
		return ret
	}
	return *o.InterNetworkInstanceFlag
}

// GetInterNetworkInstanceFlagOk returns a tuple with the InterNetworkInstanceFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetInterNetworkInstanceFlagOk() (*bool, bool) {
	if o == nil || IsNil(o.InterNetworkInstanceFlag) {
		return nil, false
	}
	return o.InterNetworkInstanceFlag, true
}

// HasInterNetworkInstanceFlag returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasInterNetworkInstanceFlag() bool {
	if o != nil && !IsNil(o.InterNetworkInstanceFlag) {
		return true
	}

	return false
}

// SetInterNetworkInstanceFlag gets a reference to the given bool and assigns it to the InterNetworkInstanceFlag field.
func (o *QueryPrefixNotificationItem) SetInterNetworkInstanceFlag(v bool) {
	o.InterNetworkInstanceFlag = &v
}

// GetMatchedPrefix returns the MatchedPrefix field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetMatchedPrefix() string {
	if o == nil || IsNil(o.MatchedPrefix) {
		var ret string
		return ret
	}
	return *o.MatchedPrefix
}

// GetMatchedPrefixOk returns a tuple with the MatchedPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetMatchedPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.MatchedPrefix) {
		return nil, false
	}
	return o.MatchedPrefix, true
}

// HasMatchedPrefix returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasMatchedPrefix() bool {
	if o != nil && !IsNil(o.MatchedPrefix) {
		return true
	}

	return false
}

// SetMatchedPrefix gets a reference to the given string and assigns it to the MatchedPrefix field.
func (o *QueryPrefixNotificationItem) SetMatchedPrefix(v string) {
	o.MatchedPrefix = &v
}

// GetNexthops returns the Nexthops field value if set, zero value otherwise.
func (o *QueryPrefixNotificationItem) GetNexthops() []QueryPrefixNotificationNexthopItem {
	if o == nil || IsNil(o.Nexthops) {
		var ret []QueryPrefixNotificationNexthopItem
		return ret
	}
	return o.Nexthops
}

// GetNexthopsOk returns a tuple with the Nexthops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationItem) GetNexthopsOk() ([]QueryPrefixNotificationNexthopItem, bool) {
	if o == nil || IsNil(o.Nexthops) {
		return nil, false
	}
	return o.Nexthops, true
}

// HasNexthops returns a boolean if a field has been set.
func (o *QueryPrefixNotificationItem) HasNexthops() bool {
	if o != nil && !IsNil(o.Nexthops) {
		return true
	}

	return false
}

// SetNexthops gets a reference to the given []QueryPrefixNotificationNexthopItem and assigns it to the Nexthops field.
func (o *QueryPrefixNotificationItem) SetNexthops(v []QueryPrefixNotificationNexthopItem) {
	o.Nexthops = v
}

func (o QueryPrefixNotificationItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryPrefixNotificationItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsFound) {
		toSerialize["isFound"] = o.IsFound
	}
	if !IsNil(o.NetworkInstance) {
		toSerialize["networkInstance"] = o.NetworkInstance
	}
	if !IsNil(o.AddressFamily) {
		toSerialize["addressFamily"] = o.AddressFamily
	}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.RetNexthopType) {
		toSerialize["retNexthopType"] = o.RetNexthopType
	}
	if !IsNil(o.NumServiceNexthop) {
		toSerialize["numServiceNexthop"] = o.NumServiceNexthop
	}
	if !IsNil(o.NumIpNexthop) {
		toSerialize["numIpNexthop"] = o.NumIpNexthop
	}
	if !IsNil(o.NumLspNexthop) {
		toSerialize["numLspNexthop"] = o.NumLspNexthop
	}
	if !IsNil(o.InterNetworkInstanceFlag) {
		toSerialize["interNetworkInstanceFlag"] = o.InterNetworkInstanceFlag
	}
	if !IsNil(o.MatchedPrefix) {
		toSerialize["matchedPrefix"] = o.MatchedPrefix
	}
	if !IsNil(o.Nexthops) {
		toSerialize["nexthops"] = o.Nexthops
	}
	return toSerialize, nil
}

type NullableQueryPrefixNotificationItem struct {
	value *QueryPrefixNotificationItem
	isSet bool
}

func (v NullableQueryPrefixNotificationItem) Get() *QueryPrefixNotificationItem {
	return v.value
}

func (v *NullableQueryPrefixNotificationItem) Set(val *QueryPrefixNotificationItem) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryPrefixNotificationItem) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryPrefixNotificationItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryPrefixNotificationItem(val *QueryPrefixNotificationItem) *NullableQueryPrefixNotificationItem {
	return &NullableQueryPrefixNotificationItem{value: val, isSet: true}
}

func (v NullableQueryPrefixNotificationItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryPrefixNotificationItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


