/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ProducerNotificationMsg - Message content.
type ProducerNotificationMsg struct {
	QueryNexthopNotification *QueryNexthopNotification
	QueryNexthopNotificationEOF *QueryNexthopNotificationEOF
	QueryPrefixNotification *QueryPrefixNotification
	QueryPrefixNotificationEOF *QueryPrefixNotificationEOF
}

// QueryNexthopNotificationAsProducerNotificationMsg is a convenience function that returns QueryNexthopNotification wrapped in ProducerNotificationMsg
func QueryNexthopNotificationAsProducerNotificationMsg(v *QueryNexthopNotification) ProducerNotificationMsg {
	return ProducerNotificationMsg{
		QueryNexthopNotification: v,
	}
}

// QueryNexthopNotificationEOFAsProducerNotificationMsg is a convenience function that returns QueryNexthopNotificationEOF wrapped in ProducerNotificationMsg
func QueryNexthopNotificationEOFAsProducerNotificationMsg(v *QueryNexthopNotificationEOF) ProducerNotificationMsg {
	return ProducerNotificationMsg{
		QueryNexthopNotificationEOF: v,
	}
}

// QueryPrefixNotificationAsProducerNotificationMsg is a convenience function that returns QueryPrefixNotification wrapped in ProducerNotificationMsg
func QueryPrefixNotificationAsProducerNotificationMsg(v *QueryPrefixNotification) ProducerNotificationMsg {
	return ProducerNotificationMsg{
		QueryPrefixNotification: v,
	}
}

// QueryPrefixNotificationEOFAsProducerNotificationMsg is a convenience function that returns QueryPrefixNotificationEOF wrapped in ProducerNotificationMsg
func QueryPrefixNotificationEOFAsProducerNotificationMsg(v *QueryPrefixNotificationEOF) ProducerNotificationMsg {
	return ProducerNotificationMsg{
		QueryPrefixNotificationEOF: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ProducerNotificationMsg) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into QueryNexthopNotification
	err = newStrictDecoder(data).Decode(&dst.QueryNexthopNotification)
	if err == nil {
		jsonQueryNexthopNotification, _ := json.Marshal(dst.QueryNexthopNotification)
		if string(jsonQueryNexthopNotification) == "{}" { // empty struct
			dst.QueryNexthopNotification = nil
		} else {
			if err = validator.Validate(dst.QueryNexthopNotification); err != nil {
				dst.QueryNexthopNotification = nil
			} else {
				match++
			}
		}
	} else {
		dst.QueryNexthopNotification = nil
	}

	// try to unmarshal data into QueryNexthopNotificationEOF
	err = newStrictDecoder(data).Decode(&dst.QueryNexthopNotificationEOF)
	if err == nil {
		jsonQueryNexthopNotificationEOF, _ := json.Marshal(dst.QueryNexthopNotificationEOF)
		if string(jsonQueryNexthopNotificationEOF) == "{}" { // empty struct
			dst.QueryNexthopNotificationEOF = nil
		} else {
			if err = validator.Validate(dst.QueryNexthopNotificationEOF); err != nil {
				dst.QueryNexthopNotificationEOF = nil
			} else {
				match++
			}
		}
	} else {
		dst.QueryNexthopNotificationEOF = nil
	}

	// try to unmarshal data into QueryPrefixNotification
	err = newStrictDecoder(data).Decode(&dst.QueryPrefixNotification)
	if err == nil {
		jsonQueryPrefixNotification, _ := json.Marshal(dst.QueryPrefixNotification)
		if string(jsonQueryPrefixNotification) == "{}" { // empty struct
			dst.QueryPrefixNotification = nil
		} else {
			if err = validator.Validate(dst.QueryPrefixNotification); err != nil {
				dst.QueryPrefixNotification = nil
			} else {
				match++
			}
		}
	} else {
		dst.QueryPrefixNotification = nil
	}

	// try to unmarshal data into QueryPrefixNotificationEOF
	err = newStrictDecoder(data).Decode(&dst.QueryPrefixNotificationEOF)
	if err == nil {
		jsonQueryPrefixNotificationEOF, _ := json.Marshal(dst.QueryPrefixNotificationEOF)
		if string(jsonQueryPrefixNotificationEOF) == "{}" { // empty struct
			dst.QueryPrefixNotificationEOF = nil
		} else {
			if err = validator.Validate(dst.QueryPrefixNotificationEOF); err != nil {
				dst.QueryPrefixNotificationEOF = nil
			} else {
				match++
			}
		}
	} else {
		dst.QueryPrefixNotificationEOF = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.QueryNexthopNotification = nil
		dst.QueryNexthopNotificationEOF = nil
		dst.QueryPrefixNotification = nil
		dst.QueryPrefixNotificationEOF = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ProducerNotificationMsg)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ProducerNotificationMsg)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ProducerNotificationMsg) MarshalJSON() ([]byte, error) {
	if src.QueryNexthopNotification != nil {
		return json.Marshal(&src.QueryNexthopNotification)
	}

	if src.QueryNexthopNotificationEOF != nil {
		return json.Marshal(&src.QueryNexthopNotificationEOF)
	}

	if src.QueryPrefixNotification != nil {
		return json.Marshal(&src.QueryPrefixNotification)
	}

	if src.QueryPrefixNotificationEOF != nil {
		return json.Marshal(&src.QueryPrefixNotificationEOF)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ProducerNotificationMsg) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.QueryNexthopNotification != nil {
		return obj.QueryNexthopNotification
	}

	if obj.QueryNexthopNotificationEOF != nil {
		return obj.QueryNexthopNotificationEOF
	}

	if obj.QueryPrefixNotification != nil {
		return obj.QueryPrefixNotification
	}

	if obj.QueryPrefixNotificationEOF != nil {
		return obj.QueryPrefixNotificationEOF
	}

	// all schemas are nil
	return nil
}

type NullableProducerNotificationMsg struct {
	value *ProducerNotificationMsg
	isSet bool
}

func (v NullableProducerNotificationMsg) Get() *ProducerNotificationMsg {
	return v.value
}

func (v *NullableProducerNotificationMsg) Set(val *ProducerNotificationMsg) {
	v.value = val
	v.isSet = true
}

func (v NullableProducerNotificationMsg) IsSet() bool {
	return v.isSet
}

func (v *NullableProducerNotificationMsg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProducerNotificationMsg(val *ProducerNotificationMsg) *NullableProducerNotificationMsg {
	return &NullableProducerNotificationMsg{value: val, isSet: true}
}

func (v NullableProducerNotificationMsg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProducerNotificationMsg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


