/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceNexthop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceNexthop{}

// ServiceNexthop Nexthop Service Local (Fabric Route) with name and (optionally) instance id.
type ServiceNexthop struct {
	// Name of the service.
	ServiceName string `json:"serviceName"`
	// Pod unique ID.
	InstanceId *string `json:"instanceId,omitempty"`
}

type _ServiceNexthop ServiceNexthop

// NewServiceNexthop instantiates a new ServiceNexthop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceNexthop(serviceName string) *ServiceNexthop {
	this := ServiceNexthop{}
	this.ServiceName = serviceName
	return &this
}

// NewServiceNexthopWithDefaults instantiates a new ServiceNexthop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceNexthopWithDefaults() *ServiceNexthop {
	this := ServiceNexthop{}
	return &this
}

// GetServiceName returns the ServiceName field value
func (o *ServiceNexthop) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *ServiceNexthop) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *ServiceNexthop) SetServiceName(v string) {
	o.ServiceName = v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *ServiceNexthop) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceNexthop) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *ServiceNexthop) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *ServiceNexthop) SetInstanceId(v string) {
	o.InstanceId = &v
}

func (o ServiceNexthop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceNexthop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serviceName"] = o.ServiceName
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	return toSerialize, nil
}

func (o *ServiceNexthop) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceNexthop := _ServiceNexthop{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceNexthop)

	if err != nil {
		return err
	}

	*o = ServiceNexthop(varServiceNexthop)

	return err
}

type NullableServiceNexthop struct {
	value *ServiceNexthop
	isSet bool
}

func (v NullableServiceNexthop) Get() *ServiceNexthop {
	return v.value
}

func (v *NullableServiceNexthop) Set(val *ServiceNexthop) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceNexthop) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceNexthop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceNexthop(val *ServiceNexthop) *NullableServiceNexthop {
	return &NullableServiceNexthop{value: val, isSet: true}
}

func (v NullableServiceNexthop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceNexthop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


