/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QueryPrefixNotificationNexthopItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryPrefixNotificationNexthopItem{}

// QueryPrefixNotificationNexthopItem struct for QueryPrefixNotificationNexthopItem
type QueryPrefixNotificationNexthopItem struct {
	// The queried address info
	AddressInfo *NexthopAddressInfo `json:"addressInfo,omitempty"`
	Metric *int32 `json:"metric,omitempty"`
	ResolvedNetworkInstanceName *string `json:"resolvedNetworkInstanceName,omitempty"`
	ProtocolType *RouteType `json:"protocolType,omitempty"`
	// Nexthop priority. The higher the value, the lower the priority
	Priority *int32 `json:"priority,omitempty"`
}

// NewQueryPrefixNotificationNexthopItem instantiates a new QueryPrefixNotificationNexthopItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryPrefixNotificationNexthopItem() *QueryPrefixNotificationNexthopItem {
	this := QueryPrefixNotificationNexthopItem{}
	return &this
}

// NewQueryPrefixNotificationNexthopItemWithDefaults instantiates a new QueryPrefixNotificationNexthopItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryPrefixNotificationNexthopItemWithDefaults() *QueryPrefixNotificationNexthopItem {
	this := QueryPrefixNotificationNexthopItem{}
	return &this
}

// GetAddressInfo returns the AddressInfo field value if set, zero value otherwise.
func (o *QueryPrefixNotificationNexthopItem) GetAddressInfo() NexthopAddressInfo {
	if o == nil || IsNil(o.AddressInfo) {
		var ret NexthopAddressInfo
		return ret
	}
	return *o.AddressInfo
}

// GetAddressInfoOk returns a tuple with the AddressInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationNexthopItem) GetAddressInfoOk() (*NexthopAddressInfo, bool) {
	if o == nil || IsNil(o.AddressInfo) {
		return nil, false
	}
	return o.AddressInfo, true
}

// HasAddressInfo returns a boolean if a field has been set.
func (o *QueryPrefixNotificationNexthopItem) HasAddressInfo() bool {
	if o != nil && !IsNil(o.AddressInfo) {
		return true
	}

	return false
}

// SetAddressInfo gets a reference to the given NexthopAddressInfo and assigns it to the AddressInfo field.
func (o *QueryPrefixNotificationNexthopItem) SetAddressInfo(v NexthopAddressInfo) {
	o.AddressInfo = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *QueryPrefixNotificationNexthopItem) GetMetric() int32 {
	if o == nil || IsNil(o.Metric) {
		var ret int32
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationNexthopItem) GetMetricOk() (*int32, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *QueryPrefixNotificationNexthopItem) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given int32 and assigns it to the Metric field.
func (o *QueryPrefixNotificationNexthopItem) SetMetric(v int32) {
	o.Metric = &v
}

// GetResolvedNetworkInstanceName returns the ResolvedNetworkInstanceName field value if set, zero value otherwise.
func (o *QueryPrefixNotificationNexthopItem) GetResolvedNetworkInstanceName() string {
	if o == nil || IsNil(o.ResolvedNetworkInstanceName) {
		var ret string
		return ret
	}
	return *o.ResolvedNetworkInstanceName
}

// GetResolvedNetworkInstanceNameOk returns a tuple with the ResolvedNetworkInstanceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationNexthopItem) GetResolvedNetworkInstanceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ResolvedNetworkInstanceName) {
		return nil, false
	}
	return o.ResolvedNetworkInstanceName, true
}

// HasResolvedNetworkInstanceName returns a boolean if a field has been set.
func (o *QueryPrefixNotificationNexthopItem) HasResolvedNetworkInstanceName() bool {
	if o != nil && !IsNil(o.ResolvedNetworkInstanceName) {
		return true
	}

	return false
}

// SetResolvedNetworkInstanceName gets a reference to the given string and assigns it to the ResolvedNetworkInstanceName field.
func (o *QueryPrefixNotificationNexthopItem) SetResolvedNetworkInstanceName(v string) {
	o.ResolvedNetworkInstanceName = &v
}

// GetProtocolType returns the ProtocolType field value if set, zero value otherwise.
func (o *QueryPrefixNotificationNexthopItem) GetProtocolType() RouteType {
	if o == nil || IsNil(o.ProtocolType) {
		var ret RouteType
		return ret
	}
	return *o.ProtocolType
}

// GetProtocolTypeOk returns a tuple with the ProtocolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationNexthopItem) GetProtocolTypeOk() (*RouteType, bool) {
	if o == nil || IsNil(o.ProtocolType) {
		return nil, false
	}
	return o.ProtocolType, true
}

// HasProtocolType returns a boolean if a field has been set.
func (o *QueryPrefixNotificationNexthopItem) HasProtocolType() bool {
	if o != nil && !IsNil(o.ProtocolType) {
		return true
	}

	return false
}

// SetProtocolType gets a reference to the given RouteType and assigns it to the ProtocolType field.
func (o *QueryPrefixNotificationNexthopItem) SetProtocolType(v RouteType) {
	o.ProtocolType = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *QueryPrefixNotificationNexthopItem) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPrefixNotificationNexthopItem) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *QueryPrefixNotificationNexthopItem) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *QueryPrefixNotificationNexthopItem) SetPriority(v int32) {
	o.Priority = &v
}

func (o QueryPrefixNotificationNexthopItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryPrefixNotificationNexthopItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressInfo) {
		toSerialize["addressInfo"] = o.AddressInfo
	}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.ResolvedNetworkInstanceName) {
		toSerialize["resolvedNetworkInstanceName"] = o.ResolvedNetworkInstanceName
	}
	if !IsNil(o.ProtocolType) {
		toSerialize["protocolType"] = o.ProtocolType
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

type NullableQueryPrefixNotificationNexthopItem struct {
	value *QueryPrefixNotificationNexthopItem
	isSet bool
}

func (v NullableQueryPrefixNotificationNexthopItem) Get() *QueryPrefixNotificationNexthopItem {
	return v.value
}

func (v *NullableQueryPrefixNotificationNexthopItem) Set(val *QueryPrefixNotificationNexthopItem) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryPrefixNotificationNexthopItem) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryPrefixNotificationNexthopItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryPrefixNotificationNexthopItem(val *QueryPrefixNotificationNexthopItem) *NullableQueryPrefixNotificationNexthopItem {
	return &NullableQueryPrefixNotificationNexthopItem{value: val, isSet: true}
}

func (v NullableQueryPrefixNotificationNexthopItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryPrefixNotificationNexthopItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


