/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsumerNexthopsNotificationItemEntryInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerNexthopsNotificationItemEntryInner{}

// ConsumerNexthopsNotificationItemEntryInner Specific content of nexthop.
type ConsumerNexthopsNotificationItemEntryInner struct {
	ViaNexthop *ConsumerNexthopsNotificationItemEntryInnerViaNexthop `json:"viaNexthop,omitempty"`
	// Nexthop address for consumer. If above \"viaNexthop\" id is present, nexthopAddress can be ignored during forwarding. Only meaningful when adding operations.
	AddressInfo *NexthopAddressInfo `json:"addressInfo,omitempty"`
	// For vpn and mpls label forwarding.
	Label *int32 `json:"label,omitempty"`
	InterfaceType *InterfaceType `json:"interfaceType,omitempty"`
	// Nexthop priority. The higher the value, the lower the priority
	Priority *int32 `json:"priority,omitempty"`
}

// NewConsumerNexthopsNotificationItemEntryInner instantiates a new ConsumerNexthopsNotificationItemEntryInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerNexthopsNotificationItemEntryInner() *ConsumerNexthopsNotificationItemEntryInner {
	this := ConsumerNexthopsNotificationItemEntryInner{}
	return &this
}

// NewConsumerNexthopsNotificationItemEntryInnerWithDefaults instantiates a new ConsumerNexthopsNotificationItemEntryInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerNexthopsNotificationItemEntryInnerWithDefaults() *ConsumerNexthopsNotificationItemEntryInner {
	this := ConsumerNexthopsNotificationItemEntryInner{}
	return &this
}

// GetViaNexthop returns the ViaNexthop field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetViaNexthop() ConsumerNexthopsNotificationItemEntryInnerViaNexthop {
	if o == nil || IsNil(o.ViaNexthop) {
		var ret ConsumerNexthopsNotificationItemEntryInnerViaNexthop
		return ret
	}
	return *o.ViaNexthop
}

// GetViaNexthopOk returns a tuple with the ViaNexthop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetViaNexthopOk() (*ConsumerNexthopsNotificationItemEntryInnerViaNexthop, bool) {
	if o == nil || IsNil(o.ViaNexthop) {
		return nil, false
	}
	return o.ViaNexthop, true
}

// HasViaNexthop returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) HasViaNexthop() bool {
	if o != nil && !IsNil(o.ViaNexthop) {
		return true
	}

	return false
}

// SetViaNexthop gets a reference to the given ConsumerNexthopsNotificationItemEntryInnerViaNexthop and assigns it to the ViaNexthop field.
func (o *ConsumerNexthopsNotificationItemEntryInner) SetViaNexthop(v ConsumerNexthopsNotificationItemEntryInnerViaNexthop) {
	o.ViaNexthop = &v
}

// GetAddressInfo returns the AddressInfo field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetAddressInfo() NexthopAddressInfo {
	if o == nil || IsNil(o.AddressInfo) {
		var ret NexthopAddressInfo
		return ret
	}
	return *o.AddressInfo
}

// GetAddressInfoOk returns a tuple with the AddressInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetAddressInfoOk() (*NexthopAddressInfo, bool) {
	if o == nil || IsNil(o.AddressInfo) {
		return nil, false
	}
	return o.AddressInfo, true
}

// HasAddressInfo returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) HasAddressInfo() bool {
	if o != nil && !IsNil(o.AddressInfo) {
		return true
	}

	return false
}

// SetAddressInfo gets a reference to the given NexthopAddressInfo and assigns it to the AddressInfo field.
func (o *ConsumerNexthopsNotificationItemEntryInner) SetAddressInfo(v NexthopAddressInfo) {
	o.AddressInfo = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetLabel() int32 {
	if o == nil || IsNil(o.Label) {
		var ret int32
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetLabelOk() (*int32, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given int32 and assigns it to the Label field.
func (o *ConsumerNexthopsNotificationItemEntryInner) SetLabel(v int32) {
	o.Label = &v
}

// GetInterfaceType returns the InterfaceType field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetInterfaceType() InterfaceType {
	if o == nil || IsNil(o.InterfaceType) {
		var ret InterfaceType
		return ret
	}
	return *o.InterfaceType
}

// GetInterfaceTypeOk returns a tuple with the InterfaceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetInterfaceTypeOk() (*InterfaceType, bool) {
	if o == nil || IsNil(o.InterfaceType) {
		return nil, false
	}
	return o.InterfaceType, true
}

// HasInterfaceType returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) HasInterfaceType() bool {
	if o != nil && !IsNil(o.InterfaceType) {
		return true
	}

	return false
}

// SetInterfaceType gets a reference to the given InterfaceType and assigns it to the InterfaceType field.
func (o *ConsumerNexthopsNotificationItemEntryInner) SetInterfaceType(v InterfaceType) {
	o.InterfaceType = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ConsumerNexthopsNotificationItemEntryInner) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *ConsumerNexthopsNotificationItemEntryInner) SetPriority(v int32) {
	o.Priority = &v
}

func (o ConsumerNexthopsNotificationItemEntryInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerNexthopsNotificationItemEntryInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ViaNexthop) {
		toSerialize["viaNexthop"] = o.ViaNexthop
	}
	if !IsNil(o.AddressInfo) {
		toSerialize["addressInfo"] = o.AddressInfo
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.InterfaceType) {
		toSerialize["interfaceType"] = o.InterfaceType
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

type NullableConsumerNexthopsNotificationItemEntryInner struct {
	value *ConsumerNexthopsNotificationItemEntryInner
	isSet bool
}

func (v NullableConsumerNexthopsNotificationItemEntryInner) Get() *ConsumerNexthopsNotificationItemEntryInner {
	return v.value
}

func (v *NullableConsumerNexthopsNotificationItemEntryInner) Set(val *ConsumerNexthopsNotificationItemEntryInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerNexthopsNotificationItemEntryInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerNexthopsNotificationItemEntryInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerNexthopsNotificationItemEntryInner(val *ConsumerNexthopsNotificationItemEntryInner) *NullableConsumerNexthopsNotificationItemEntryInner {
	return &NullableConsumerNexthopsNotificationItemEntryInner{value: val, isSet: true}
}

func (v NullableConsumerNexthopsNotificationItemEntryInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerNexthopsNotificationItemEntryInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


