/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RouteNexthopInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouteNexthopInfo{}

// RouteNexthopInfo struct for RouteNexthopInfo
type RouteNexthopInfo struct {
	// Network instance.
	NetworkInstance *string `json:"networkInstance,omitempty"`
	// Attributes of the nexthop of the route. Some attributes makes others mandatory:   - vpn_label: the vpn_label of labels field must be filled   - label: the label of labels field must be filled   - service_local: the addressInfo must be filled with a service type
	Attr []RouteNexthopInfoAttrInner `json:"attr,omitempty"`
	AddressInfo NexthopAddressInfo `json:"addressInfo"`
	// Interface info.
	InterfaceInfo *InterfaceInfo `json:"interfaceInfo,omitempty"`
	// label info.
	Labels *NexthopLabels `json:"labels,omitempty"`
	// Nexthop priority. The higher the value, the lower the priority
	Priority *int32 `json:"priority,omitempty"`
}

type _RouteNexthopInfo RouteNexthopInfo

// NewRouteNexthopInfo instantiates a new RouteNexthopInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouteNexthopInfo(addressInfo NexthopAddressInfo) *RouteNexthopInfo {
	this := RouteNexthopInfo{}
	this.AddressInfo = addressInfo
	return &this
}

// NewRouteNexthopInfoWithDefaults instantiates a new RouteNexthopInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteNexthopInfoWithDefaults() *RouteNexthopInfo {
	this := RouteNexthopInfo{}
	return &this
}

// GetNetworkInstance returns the NetworkInstance field value if set, zero value otherwise.
func (o *RouteNexthopInfo) GetNetworkInstance() string {
	if o == nil || IsNil(o.NetworkInstance) {
		var ret string
		return ret
	}
	return *o.NetworkInstance
}

// GetNetworkInstanceOk returns a tuple with the NetworkInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteNexthopInfo) GetNetworkInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkInstance) {
		return nil, false
	}
	return o.NetworkInstance, true
}

// HasNetworkInstance returns a boolean if a field has been set.
func (o *RouteNexthopInfo) HasNetworkInstance() bool {
	if o != nil && !IsNil(o.NetworkInstance) {
		return true
	}

	return false
}

// SetNetworkInstance gets a reference to the given string and assigns it to the NetworkInstance field.
func (o *RouteNexthopInfo) SetNetworkInstance(v string) {
	o.NetworkInstance = &v
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *RouteNexthopInfo) GetAttr() []RouteNexthopInfoAttrInner {
	if o == nil || IsNil(o.Attr) {
		var ret []RouteNexthopInfoAttrInner
		return ret
	}
	return o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteNexthopInfo) GetAttrOk() ([]RouteNexthopInfoAttrInner, bool) {
	if o == nil || IsNil(o.Attr) {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *RouteNexthopInfo) HasAttr() bool {
	if o != nil && !IsNil(o.Attr) {
		return true
	}

	return false
}

// SetAttr gets a reference to the given []RouteNexthopInfoAttrInner and assigns it to the Attr field.
func (o *RouteNexthopInfo) SetAttr(v []RouteNexthopInfoAttrInner) {
	o.Attr = v
}

// GetAddressInfo returns the AddressInfo field value
func (o *RouteNexthopInfo) GetAddressInfo() NexthopAddressInfo {
	if o == nil {
		var ret NexthopAddressInfo
		return ret
	}

	return o.AddressInfo
}

// GetAddressInfoOk returns a tuple with the AddressInfo field value
// and a boolean to check if the value has been set.
func (o *RouteNexthopInfo) GetAddressInfoOk() (*NexthopAddressInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddressInfo, true
}

// SetAddressInfo sets field value
func (o *RouteNexthopInfo) SetAddressInfo(v NexthopAddressInfo) {
	o.AddressInfo = v
}

// GetInterfaceInfo returns the InterfaceInfo field value if set, zero value otherwise.
func (o *RouteNexthopInfo) GetInterfaceInfo() InterfaceInfo {
	if o == nil || IsNil(o.InterfaceInfo) {
		var ret InterfaceInfo
		return ret
	}
	return *o.InterfaceInfo
}

// GetInterfaceInfoOk returns a tuple with the InterfaceInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteNexthopInfo) GetInterfaceInfoOk() (*InterfaceInfo, bool) {
	if o == nil || IsNil(o.InterfaceInfo) {
		return nil, false
	}
	return o.InterfaceInfo, true
}

// HasInterfaceInfo returns a boolean if a field has been set.
func (o *RouteNexthopInfo) HasInterfaceInfo() bool {
	if o != nil && !IsNil(o.InterfaceInfo) {
		return true
	}

	return false
}

// SetInterfaceInfo gets a reference to the given InterfaceInfo and assigns it to the InterfaceInfo field.
func (o *RouteNexthopInfo) SetInterfaceInfo(v InterfaceInfo) {
	o.InterfaceInfo = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *RouteNexthopInfo) GetLabels() NexthopLabels {
	if o == nil || IsNil(o.Labels) {
		var ret NexthopLabels
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteNexthopInfo) GetLabelsOk() (*NexthopLabels, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *RouteNexthopInfo) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given NexthopLabels and assigns it to the Labels field.
func (o *RouteNexthopInfo) SetLabels(v NexthopLabels) {
	o.Labels = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *RouteNexthopInfo) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteNexthopInfo) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *RouteNexthopInfo) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *RouteNexthopInfo) SetPriority(v int32) {
	o.Priority = &v
}

func (o RouteNexthopInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouteNexthopInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkInstance) {
		toSerialize["networkInstance"] = o.NetworkInstance
	}
	if !IsNil(o.Attr) {
		toSerialize["attr"] = o.Attr
	}
	toSerialize["addressInfo"] = o.AddressInfo
	if !IsNil(o.InterfaceInfo) {
		toSerialize["interfaceInfo"] = o.InterfaceInfo
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

func (o *RouteNexthopInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"addressInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRouteNexthopInfo := _RouteNexthopInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRouteNexthopInfo)

	if err != nil {
		return err
	}

	*o = RouteNexthopInfo(varRouteNexthopInfo)

	return err
}

type NullableRouteNexthopInfo struct {
	value *RouteNexthopInfo
	isSet bool
}

func (v NullableRouteNexthopInfo) Get() *RouteNexthopInfo {
	return v.value
}

func (v *NullableRouteNexthopInfo) Set(val *RouteNexthopInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteNexthopInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteNexthopInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteNexthopInfo(val *RouteNexthopInfo) *NullableRouteNexthopInfo {
	return &NullableRouteNexthopInfo{value: val, isSet: true}
}

func (v NullableRouteNexthopInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteNexthopInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


