/*
Routing Information Base API

API for Routing Information Base.

API version: 2.0.0
Contact: PDLDPDEVEL@pdl.internal.ericsson.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProducerNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProducerNotification{}

// ProducerNotification struct for ProducerNotification
type ProducerNotification struct {
	// Indicates client name, for either Producer or Consumer. For route-engine, client name is like {cre-pod-name} + {static/bgp/ifm}, for data-plane, client name is like {dp-pod-name}, for client that is service, client name is like {service-name}.
	ProducerId *string `json:"producerId,omitempty"`
	Msg *ProducerNotificationMsg `json:"msg,omitempty"`
}

// NewProducerNotification instantiates a new ProducerNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProducerNotification() *ProducerNotification {
	this := ProducerNotification{}
	return &this
}

// NewProducerNotificationWithDefaults instantiates a new ProducerNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProducerNotificationWithDefaults() *ProducerNotification {
	this := ProducerNotification{}
	return &this
}

// GetProducerId returns the ProducerId field value if set, zero value otherwise.
func (o *ProducerNotification) GetProducerId() string {
	if o == nil || IsNil(o.ProducerId) {
		var ret string
		return ret
	}
	return *o.ProducerId
}

// GetProducerIdOk returns a tuple with the ProducerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProducerNotification) GetProducerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProducerId) {
		return nil, false
	}
	return o.ProducerId, true
}

// HasProducerId returns a boolean if a field has been set.
func (o *ProducerNotification) HasProducerId() bool {
	if o != nil && !IsNil(o.ProducerId) {
		return true
	}

	return false
}

// SetProducerId gets a reference to the given string and assigns it to the ProducerId field.
func (o *ProducerNotification) SetProducerId(v string) {
	o.ProducerId = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *ProducerNotification) GetMsg() ProducerNotificationMsg {
	if o == nil || IsNil(o.Msg) {
		var ret ProducerNotificationMsg
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProducerNotification) GetMsgOk() (*ProducerNotificationMsg, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *ProducerNotification) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given ProducerNotificationMsg and assigns it to the Msg field.
func (o *ProducerNotification) SetMsg(v ProducerNotificationMsg) {
	o.Msg = &v
}

func (o ProducerNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProducerNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProducerId) {
		toSerialize["producerId"] = o.ProducerId
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	return toSerialize, nil
}

type NullableProducerNotification struct {
	value *ProducerNotification
	isSet bool
}

func (v NullableProducerNotification) Get() *ProducerNotification {
	return v.value
}

func (v *NullableProducerNotification) Set(val *ProducerNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableProducerNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableProducerNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProducerNotification(val *ProducerNotification) *NullableProducerNotification {
	return &NullableProducerNotification{value: val, isSet: true}
}

func (v NullableProducerNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProducerNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


