[program:http3_client_wrapper]
command     =  /usr/bin/python3 /usr/app/client_wrapper.py
directory   =  /usr/app/
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_client_wrapper.log
