[program:http3_server_ipv4_a]
command     =  /usr/app/bin/http3server 0.0.0.0 443 /usr/app/cert.key /usr/app/cert.crt --quiet --dl-bandwidth 200M
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv4_a.log

[program:http3_server_ipv4_b]
command     =  /usr/app/bin/http3server 0.0.0.0 4433 /usr/app/cert.key /usr/app/cert.crt --quiet --dl-bandwidth 2G
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv4_b.log

[program:http3_server_ipv4_c]
command     =  /usr/app/bin/http3server 0.0.0.0 6443 /usr/app/cert.key /usr/app/cert.crt --quiet --dl-bandwidth 5G
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv4_c.log

[program:http3_server_ipv4_d]
command     =  /usr/app/bin/http3server 0.0.0.0 8443 /usr/app/cert.key /usr/app/cert.crt --quiet
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv4_d.log

[program:http3_server_ipv4_e]
command     =  /usr/app/bin/http3server 0.0.0.0 1443 /usr/app/cert.key /usr/app/cert.crt --quiet --dl-bandwidth 10M
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv4_e.log

[program:http3_server_ipv4_f]
command     =  /usr/app/bin/http3server 0.0.0.0 9443 /usr/app/cert.key /usr/app/cert.crt --quiet --dl-bandwidth 1G
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv4_f.log

[program:http3_server_ipv4_g]
command     =  /usr/app/bin/http3server 0.0.0.0 2443 /usr/app/cert.key /usr/app/cert.crt --quiet --dl-bandwidth 250M
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv4_g.log



[program:http3_server_ipv6]
command     =  /usr/app/bin/http3server :: 443 /usr/app/cert.key /usr/app/cert.crt --quiet 
directory   = ./
user        = root
startsecs   = 5

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /var/log/http3_server_ipv6.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log

[program:dnsmasq]
command=dnsmasq -k
autostart=true
autorestart=true
stderr_logfile=/var/log/dnsmasq.log
stdout_logfile=/var/log/dnsmasq.log

[program:http_server]
command=/usr/app/bin/http-server -port 8080 
autostart=true
autorestart=true
stderr_logfile=/var/log/http-server-error.log
stdout_logfile=/var/log/http-server-access.log


